### ISSUE TITLE
MaterialFileUploader- uploaded files list covers fab buttons

### ISSUE THREAD

**Issue by masterdany88** [GwtMaterialDesign/gwt-material-addins#103]
On same page where I have FAB buttons I have also MaterialFileUploader.
![image](https://cloud.githubusercontent.com/assets/1161910/16416339/0fc13e2a-3d42-11e6-8066-e415e62aa3c0.png)
When I upload file, the file list panel covers completely my FAB button.
![image](https://cloud.githubusercontent.com/assets/1161910/16416329/026ce792-3d42-11e6-90cf-5b3d7fb604ae.png)

What would be the best way to deal with it?

**Comment by KenMills** [comment]
I have a similar issue where my file uploader is in a modal dialog.
The upload progress widget is mostly outside the dialog view area and can't be seen.

Is there a way to set the x/y position of the upload progress widget?

**Comment by kevzlou7979** [comment]
I will close this issue, as you can easily set the style thru css like for example:
To move the Uploaded File List Panel.
```css
.preview-container {
    right: 200px !important;
}
```
