### ISSUE TITLE
MaterialFileUploader- adding overall progressbar when adding multiple files at once

### ISSUE THREAD

**Issue by masterdany88** [GwtMaterialDesign/gwt-material-addins#104]
Hey. Did You consider to add overall progress bar for multiple file upload?
Currently is `addTotalUploadProgressHandler` and `TotalUploadProgressEvent` which give info for currently uploading file only. IMHO total name makes people think it will be for all files, not for current. I propose to change it's name to `addCurrentUploadProgressHandler` and `CurrentUploadProgressEvent`.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/6fef3865e69893be0f62b5e69fd4bbe1f317aab0
