### ISSUE TITLE
No possibility to deactivate dropzone of RichEditor 

### ISSUE THREAD

**Issue by david2411** [GwtMaterialDesign/gwt-material-addins#105]
Hey,
we use drag and drop at one point in our application. Unfortunately the rich editor activates his dropzone once we start dragging an element. In our case we do not want to drop something into the rich editor. Beside the fact, that our dragged element would not be a meaningful value for a rich editor.

There is no possibility to  switch of the drag/drop functionality for rich editor. So our current workaround is to remove the 'dropzone' div of the rich edtior with JNDI - but that is IMO a very horrible way, i hope you agree with me.
Could you provide a method to deactivate drag/drop?

**Comment by kevzlou7979** [comment]
Ok I added a disableDragAndDrop() https://github.com/GwtMaterialDesign/gwt-material-addins/commit/2291296366ea25cae4972d99bb638c60be403733.

**Comment by david2411** [comment]
Hey,
yeah u added the function, but it does not work. Still using my JNDI method is the only possibility to remove the dropzone. I do not want to see it anymore, also if it is disabled. For future searchs, my solution:

public static native void removeDropzone(String parentId) /*-{
    $wnd.$("#" + parentId + " .note-dropzone").remove();
}-*/;
