### ISSUE TITLE
MaterialStepper: vertical design is not friendly to small screens

### ISSUE THREAD

**Issue by gilberto-torrezan** [GwtMaterialDesign/gwt-material-addins#11]
This is a screenshot from the online demo with a small screen:

![screen shot 2016-01-08 at 19 11 59](https://cloud.githubusercontent.com/assets/7464735/12209699/0498b222-b63c-11e5-9a2c-b37c3ba647da.png)

The padding of the step should be smaller overall, to better accommodate the body of the step. Also note that the description text doesn't create a new line, and the text appears strange.

**Comment by kevzlou7979** [comment]
Ok will check this out

**Comment by kevzlou7979** [comment]
![image](https://cloud.githubusercontent.com/assets/3138071/13213172/e49a9f76-d981-11e5-98d7-2d04a4d242f7.png)

Ok fixed the padding , I've decrease the padding to 12px , Also the showcase app when it's mobile the padding is now consistent.

**Comment by kevzlou7979** [comment]
I've fixed also the description label, to have a correct line-height

**Comment by kevzlou7979** [comment]
![image](https://cloud.githubusercontent.com/assets/3138071/13213241/6197c710-d982-11e5-86e5-a145b32ae3fa.png)
