### ISSUE TITLE
MaterialRichEditor codeview does not refresh

### ISSUE THREAD

**Issue by david2411** [GwtMaterialDesign/gwt-material-addins#111]
Codeview of MaterialRichEditor does not refresh and shows old code, if i setHTML of the MaterialRichEditor to another value programmatically.

**Comment by kevzlou7979** [comment]
Hi there, Please ellaborate more steps, as i can't reproduce the bug itself.
![bug-8-10](https://cloud.githubusercontent.com/assets/3138071/17541856/380d666c-5ef6-11e6-9c39-09ba9df96a65.gif)
