### ISSUE TITLE
No ChangeHandling for MaterialRichEditor possible

### ISSUE THREAD

**Issue by david2411** [GwtMaterialDesign/gwt-material-addins#113]
The only workaround is to add key/click handlers and to add your own style to show active focus (blue bottom border) or valid inputs (green bottom border).
Although you do handling like this, you have not the same changed-status like the undo history. In my application e.g. i managed change of MaterialRichEditor and show dirty style. But undo jumps 2 steps back - so my "onchange" is not the same as undo-histories "onchange".

Please please please add a consistent change handling, which can be listened by the user. The valid / active style would be great!

**Comment by kevzlou7979** [comment]
Hi David,

Thanks for this issue, We will implement the ValueChange event on the rich editor. Also the valid and invalidate will be done also. 

Best Regards,
Kevin

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/b75a73dd661f1fa087be1362a87d476549f03b09

**Comment by kevzlou7979** [comment]
![rich-editor](https://cloud.githubusercontent.com/assets/3138071/17517107/6a8720b0-5e74-11e6-9eb9-ed5344e5282f.gif)
