### ISSUE TITLE
MaterialTimePicker not shown above modal

### ISSUE THREAD

**Issue by invader35** [GwtMaterialDesign/gwt-material-addins#13]
The MaterialTimePicker is not shown when a modal dialog is displayed.

Is there a configuration that I am missing or just a minor implementation bug?

**Comment by kevzlou7979** [comment]
I set the z-index with the same depth of the datepicker 
https://github.com/GwtMaterialDesign/gwt-material-addins/commit/7c70ed766ed8e287bf43dfc01580701f46fbbdd6

![time_picker_depth_issue](https://cloud.githubusercontent.com/assets/3138071/13209963/27f1618c-d965-11e5-990b-97b3df55328d.gif)
