### ISSUE TITLE
MaterialWindow add Escape key down handler

### ISSUE THREAD

**Issue by masterdany88** [GwtMaterialDesign/gwt-material-addins#132]
I would like to close material window using Escape key on keyboard. For inputs I've done it that way:
```
        KeyDownHandler keyEnterDownHandler = new KeyDownHandler() {
            @Override
            public void onKeyDown(KeyDownEvent event) {
                if (event.getNativeKeyCode() == KeyCodes.KEY_ENTER) {
                    getUiHandlers().onLoginButtonClick();
                }
            }
        };
        email.addKeyDownHandler(keyEnterDownHandler);
        password.addKeyDownHandler(keyEnterDownHandler);
```
but unfortunatelly MaterialWindow doesn't have method: `addKeyDownHandler`. Please help.
It's really pissing me that I have to close window with clicking on X

**Comment by kevzlou7979** [comment]
You can extend the Window so that you can implement your desired interface as easy fix. We will add this on next release

**Comment by masterdany88** [comment]
So I will extend `MaterialWindow` and in this extended class I will implement `HasKeyDownHandlers`?

**Comment by kevzlou7979** [comment]
Yes youre right

**Comment by masterdany88** [comment]
I'll give a try.

**Comment by BenDol** [comment]
In 2.0 I have already moved general Interaction methods into MaterialWidget to make this possible easily.

**Comment by kevzlou7979** [comment]
This one will be ready on 2.0
