### ISSUE TITLE
MaterialAutocomplete Chip placeholder bug

### ISSUE THREAD

**Issue by paulux84** [GwtMaterialDesign/gwt-material-addins#143]
Pre filling a MaterialAutocomplete type Chips with value result in following placeholder visualization
![image](https://cloud.githubusercontent.com/assets/7997728/19267388/b965b622-8fae-11e6-8e15-fff0c996a90c.png)
instead of this one 
![image](https://cloud.githubusercontent.com/assets/7997728/19267429/e7e43e88-8fae-11e6-99be-d0f02b9f5808.png)

As you can see the placeholder still remain not active so elements are overlayed.

**Comment by kevzlou7979** [comment]
Are you using gmd 2.0

**Comment by paulux84** [comment]
No, i'm using last release 1.6.0

**Comment by paulux84** [comment]
P.s. in the previous release all work

**Comment by paulux84** [comment]
@kevzlou7979 I've done the fix (https://github.com/paulux84/gwt-material-addins/tree/release_1.6.2)...in another emergency branch...1.6.2. The base branch is relese_1.6.0
Can you do a release?
Thanks

**Comment by kevzlou7979** [comment]
Ok I will create a 1.6.2 branch. Then we can call it as 1.6.2 release for addins.

**Comment by kevzlou7979** [comment]
I have created a branch ready for 1.6.2 release just submit pr and make release_1.6.2 as base branch and we are ready to go :)

**Comment by paulux84** [comment]
PR #145 done

**Comment by kevzlou7979** [comment]
Thanks for this

**Comment by paulux84** [comment]
@kevzlou7979 in the same branch i've also replaced MaterialAvatar to use Gravatar.
Intially i've maded a different class, but they do the same things in default config so i've replaced it.

**Comment by kevzlou7979** [comment]
@paulux84 Thanks great job :)

**Comment by kevzlou7979** [comment]
I tested the gravatar offline but it does not work. The current Avatar implementation works even its offline.

**Comment by paulux84** [comment]
Obviously...probably we can mix old implementation with new: if offline we call jdenticon or previously downloaded MisteryMan.
What do you think

**Comment by paulux84** [comment]
Consider that avatar are always related to a specific user...and if you would a user detail like for example username or email you must do an "ONLINE" call to your server

**Comment by kevzlou7979** [comment]
I Agree to your proposal about the Old Implementation and New Implementation. 
We can stay as it is the Old implementation and check whether its ```jdenticon``` else we will make use of the other gravatar Online API's

**Comment by kevzlou7979** [comment]
I've tested your Avatar into demo showcase but it returns an error
![image](https://cloud.githubusercontent.com/assets/3138071/19421251/fa802d70-942e-11e6-964e-6ea31fe5130f.png)

**Comment by kevzlou7979** [comment]
Also Jdenticon https://jdenticon.com/#icon-a and Identicon http://identicon.net/ are two different things.

**Comment by kevzlou7979** [comment]
I am making revisions now on MaterialAvatar - probably will make jDenticon as default avatar type also I 've fixed some code style issues (spaces and tabs).

**Comment by kevzlou7979** [comment]
Also enums must be all caps, I saw you have mm, identicon etc. it must be MM, IDENTICON because its enum. :)

**Comment by kevzlou7979** [comment]
I will apply only the Autocomplete Fixed , the Avatar thing will be patched on 2.0 (As it will be a Avatar 2.0 version). To avoid regressions.

**Comment by paulux84** [comment]
ok great.
Sorry for absence.
When you have deploy the 1.6.2 release?
Thanks

**Comment by kevzlou7979** [comment]
We are planning it tomorrow.

**Comment by kevzlou7979** [comment]
Ok just release today addins 1.6.2 thru Maven with this fixed. It will take a while to be sync on Maven Central.
