### ISSUE TITLE
ComboBox - GetValues for multiple select.

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material-addins#144]
With the recent changes https://github.com/GwtMaterialDesign/gwt-material-addins/pull/129/commits/4bfe8abb8a8a139114051a1e59b685b9265d0b0d, the combobox getValues() does not work correctly for multiple select.

Screenshot:
![combobox_issue](https://cloud.githubusercontent.com/assets/3138071/19330488/4bb25a90-9111-11e6-8382-3b5ef76c24ad.gif)

Code Resources:
https://github.com/GwtMaterialDesign/gwt-material-demo/tree/mk_api_work/src/main/java/gwt/material/design/demo/client/application/addins/combobox

**Comment by BenDol** [comment]
Resolved in https://github.com/GwtMaterialDesign/gwt-material-addins/commit/a6f4f5c55955e89b2860db20e534fa6ca85370bf

**Comment by kevzlou7979** [comment]
I have still the issue on my side tested on bd_api_work branch on gwt-material-demo
