### ISSUE TITLE
ScrollFire not work with clipped overflow

### ISSUE THREAD

**Issue by paulux84** [GwtMaterialDesign/gwt-material-addins#149]
If the body have a clipped overflow like for example overflow:scroll no ScrollFire event are raised

**Comment by kevzlou7979** [comment]
Can you give a display wherein the scroll fire is not firing, thanks

**Comment by kevzlou7979** [comment]
Ok got it fixed. ``` height: 100%; ``` was the culprit, so in order to fixed it you must assign ``` height: initial ``` to your body element http://stackoverflow.com/questions/5686629/jquery-window-scroll-event-does-not-fire-up
