### ISSUE TITLE
FileUploader not working in Safari on macOS 10.12.1

### ISSUE THREAD

**Issue by rmraya** [GwtMaterialDesign/gwt-material-addins#153]
Hi,

FileUploader does not work when used from Safari on macOS Sierra 10.12.1. Works fine from Chrome and Firefox.

The demo project at http://gwtmaterialdesign.github.io/gwt-material-demo/#fileuploader can be used for testing.

Regards,
Rodolfo M. Raya

**Comment by kevzlou7979** [comment]
I am able to reproduce the issue on browserstack thanks for catching this issue. Will provide a fix later.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/f7a4bd43d1c6885376c817468624513e95ae525d. Snapshot has been updated.
