### ISSUE TITLE
MaterialComboBox setAcceptableValues is not setting indexes.

### ISSUE THREAD

**Issue by chinshaw** [GwtMaterialDesign/gwt-material-addins#154]
When I create a MaterialComboBox and invoke setAcceptableValues the combo box will show the values correctly. However the value will always be null. I tracked it down to the getSelectedIndex() is always returning -1. 

If I use addItem(String, T) the combo box works correctly and returns the correct index for the value.

A quick look shows a divergence in how the Option is added with addItem(T value) and addItem(String text, T value).

**Comment by kevzlou7979** [comment]
Nice catch let me check this out

**Comment by chinshaw** [comment]
I was using the 2.0-SNAPSHOT.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/4ab18de7d5372e5516153924587dba157efa4117
