### ISSUE TITLE
Color.fromStyleNames() return wrong css style name in EnumHelper class

### ISSUE THREAD

**Issue by drmzperx** [GwtMaterialDesign/gwt-material-addins#159]
hi!

Maybe the EnumHelper class return wrong css style name while the enumeration, because I get e.g. "PINK" color for the "pink lighten-4" css style name.

gwt-material 2.0-rc1

Thanks!

**Comment by kevzlou7979** [comment]
I think it's because of the space between ``` pink ``` and ``` lighten-4```

**Comment by BenDol** [comment]
https://github.com/GwtMaterialDesign/gwt-material/blob/master/gwt-material/src/main/java/gwt/material/design/client/constants/Color.java#L315
