### ISSUE TITLE
MaterialTree: No encapsulated method to unselect current selection

### ISSUE THREAD

**Issue by Hoagiex** [GwtMaterialDesign/gwt-material-addins#163]
To unselect/unset the selected MaterialTreeItem, you currently need to call several methods from a custom subclass:

```
MaterialTreeItem selectedItem = getSelectedItem();
clearItemSelectedStyles(selectedItem);
setSelectedItem(null);
SelectionEvent.fire(this, null);
```

It would be nice, if all this logic was encapsulated in a single method (e.g. 'deselectSelectedItem()')

**Comment by kevzlou7979** [comment]
+1

**Comment by kevzlou7979** [comment]
I would suggest ``` deselectItem() ```.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/c5370d45a643369ad5e44079efac4ea2946182de
