### ISSUE TITLE
MaterialTimePicker no ValueChangedEvent being fired

### ISSUE THREAD

**Issue by silentsnooc** [GwtMaterialDesign/gwt-material-addins#17]
I am not sure how to fix this. I tried to add the firing of the event to `setText(String)` but it seems like the value of the underlying textbox is changed in another way.

However, it would be nice to be able to catch a ValueChangedEvent for *Picker.

**Comment by kevzlou7979** [comment]
Ok with the PR you contributed the time picker supports now value change event https://github.com/GwtMaterialDesign/gwt-material-addins/commit/4a905b2e71f8d15b340b63d955d5fdd8ddf27e7d
