### ISSUE TITLE
MaterialComboBox: Remove / clear items

### ISSUE THREAD

**Issue by luizmineo** [GwtMaterialDesign/gwt-material-addins#170]
Is there a way to remove all items from a MaterialComboBox, or maybe set a new List of items? So far, I've tried these methods, but without success:

```Java
comboBox.clear(); //somehow combobox is destroyed
comboBox.setAcceptableValues(values); //calling it twice has the same effect of clear()
```

For now, I'm removing comboBox from parent and building a new one as workaround.

**Comment by kevzlou7979** [comment]
Do you mean by clear() is to clear ComboBox Options (Dropdown options). ?
