### ISSUE TITLE
ComboBox setValue is not working for the first element.

### ISSUE THREAD

**Issue by sschedl** [GwtMaterialDesign/gwt-material-addins#171]
Hello,

using setValue on the comboBox is not working for the first element of the list  of values from the box.
```
    @Override
    public void setValue(T value, boolean fireEvents) {
        int index = values.indexOf(value);
        if (index > 0) {
            T before = getValue();
            setSelectedIndex(index);

            if (fireEvents) {
                ValueChangeEvent.fireIfNotEqual(this, before, value);
            }
        }
    }
```

I think `index >0` should be `index >= 0`

Best Regards

Stefan

**Comment by kevzlou7979** [comment]
Good catch, thanks for catching this issue.
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/0a7baa0f6c72d2ce6c6e89230beb70b668b9d850
