### ISSUE TITLE
Window closes first the content and then the buttons

### ISSUE THREAD

**Issue by andrescirulo** [GwtMaterialDesign/gwt-material-addins#172]
When you close the Window widget, the content dissapears inmediatly, but the close and maximize buttons in the toolbar stay there for a second and then dissapear. 
The behaviour can be seen in the demo page.

**Comment by kevzlou7979** [comment]
I investigate this issue deeply and it seems that the  css property ```visibility: hidden / visible``` is the real culprit of the closing animation. The workaround is to use ```display: block / none```.

Fixed via 
https://github.com/GwtMaterialDesign/gwt-material-addins/commit/732b246a637c1ea7597d266bb065b1eadcc03814
