### ISSUE TITLE
MaterialFileUploader throws ClassCastException when compiled for production

### ISSUE THREAD

**Issue by vpoilvert** [GwtMaterialDesign/gwt-material-addins#177]
The MaterialFileUploader is broken when I compile my GWT application for production (ie with optimizationLevel=9), it throws a ClassCastException. Further tests show that it does not work when optimizationLevel is greater than 0.

This is the code written in MaterialFileUploader :
```java
uploader.on("uploadprogress", (progress, file, response) -> {
            CurrentUploadProgressEvent.fire(this, progress);
            if ($this != null) {
                $this.find(".progress .determinate").css("width", progress + "%");
            }
        });
```

This is the code generated with optimizationLevel=9 and style=PRETTY :
```javascript
this$static.uploader.on('uploadprogress', makeLambdaFunction(MaterialFileUploader$lambda$10$Type.prototype.call_2, MaterialFileUploader$lambda$10$Type, [this$static]));
[...]
defineClass(1360, $wnd.Function, {}, MaterialFileUploader$lambda$10$Type);
_.call_2 = function call_3(arg0, arg1, arg2){
  $clinit_CurrentUploadProgressEvent();
  $fireEvent(this.$$outer_0, (checkNotNull((checkCriticalType(arg0 == null || instanceOfDouble(arg0)) , arg0)) , new CurrentUploadProgressEvent));
}
```

This code looks good but if I put a breakpoint using Chrome developer tools I can see that the arguments order is messed up. arg0 is the file and arg1 is the progress.

The problem is also present in Super Dev Mode but it does not throw a ClassCastException.

Libraries versions : 
- GWT : 2.8
- GWT Material + Themes + Addins : 2.0-rc3

**Comment by kevzlou7979** [comment]
On the latest release this could be fixed. Try to reopen if still exist on 2.0-rc7 (WIP release)
