### ISSUE TITLE
Window size in function of screen size ?

### ISSUE THREAD

**Issue by reofake** [GwtMaterialDesign/gwt-material-addins#180]
Actually, the window only have a "width" attribute for all screen size. I think this would be interesting to have the possibility to change the width of the window depending on the screen size.

**Comment by kevzlou7979** [comment]
Hi there you can make use of Css Media Queries to alter the css styles you want to update. http://www.w3schools.com/cssref/css3_pr_mediaquery.asp

**Comment by reofake** [comment]
This is a solution, but it would be really interesting to have something like the "grid" param.

**Comment by kevzlou7979** [comment]
On 2.1, We added ViewPort Helper to help users detect the screen width and set specific callbacks when they are on specific browser window size. So this will help you set the width of the Window component.

Note: Viewport helper only added on 2.1.
