### ISSUE TITLE
Param toolbarColor of window ignored

### ISSUE THREAD

**Issue by reofake** [GwtMaterialDesign/gwt-material-addins#181]
Duplicate of https://github.com/GwtMaterialDesign/gwt-material/issues/522 to reopen (on the good project this time :) ).

The param toolbarColor of window is ignored in XML and in Java.

The color used is the color of the theme (2.0-rc3).
And with the 2.0-SNAPSHOT version, the color used is always blue. So for me this commit is not the solution : GwtMaterialDesign/gwt-material-themes@ea4dcc2

**Comment by reofake** [comment]
I just migrate to 2.0-rc4 and now all the windows'toolbars are blue.

**Comment by kevzlou7979** [comment]
Fixed via GwtMaterialDesign/gwt-material-addins@fe60e3f.

Added Test Demo here
https://github.com/GwtMaterialDesign/gwt-material-issue-test/tree/%23591

**Comment by reofake** [comment]
I confirm this is OK for me !

**Comment by kevzlou7979** [comment]
@reofake  Nice to hear :)
