### ISSUE TITLE
[2.1] MaterialFileUploader problem with 'maxFileSize'

### ISSUE THREAD

**Issue by richelivargas** [GwtMaterialDesign/gwt-material-addins#185]
MaterialFileUploader dosen't throw exception when max size of file is exceeded.

**Comment by kevzlou7979** [comment]
The File Uploader throws Max Size exception if I set ```maxFileSize="1" ``` if your server response is correct (Make sure you have a working server else the error prompts ```There's a problem uploading your file.``` which returns 404). Please provide your code. Thanks in advance
