### ISSUE TITLE
[1.6.2] MaterialAutocomplete Suggestion Chip placeholder bug

### ISSUE THREAD

**Issue by chadluo** [GwtMaterialDesign/gwt-material-addins#187]
What's fixed in #143 seems only work for `String` values. If you are dealing with `Suggestion`s you might need [similar fixes](https://github.com/GwtMaterialDesign/gwt-material-addins/blob/master/src/main/java/gwt/material/design/addins/client/autocomplete/MaterialAutoComplete.java#L770) for that.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/7dc151c3f8eb8a64c62809707c5c6728145786e7
