### ISSUE TITLE
class MaterialOverlayTab is missing in 2.0-SNAPSHOT

### ISSUE THREAD

**Issue by ingosch** [GwtMaterialDesign/gwt-material-addins#191]
Cloned the 2.0-SNAPSHOT branch from github and the class MaterialOverlayTab is missing in package gwt.material.design.addins.client.overlay.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/09e7aa0b0525070069d387c8f470dbc49f9c37ea. Thanks for catching this, as MaterialOverlayTab will be added thru 2.1-SNAPSHOT instead
