### ISSUE TITLE
MaterialComboBox: inconsitent use of keyFactory

### ISSUE THREAD

**Issue by tbenbrahim** [GwtMaterialDesign/gwt-material-addins#192]
There are many places in the code that use value.ToString rather than keyFactory.generateKey, for example setSelectedIndex. PR is forthcoming to replace all value.ToString() calls

For discussion: I find the keyFactory name very misleading and the class is unnecessary.
In my opinion (both of these can be treated independently):
- it is should be called displayNameSupplier or displayNameFactory, the point is `key` is misleading. The "key" of my models is `id`, the "display name" of my models is`name`, so we are clearly not talking about keys here 
- in 2.x, it should be a Function<T, String> rather than a dedicated class.

**Comment by kevzlou7979** [comment]
Let's marked it as a discussion so that we can hear other dev opinion about the naming of class changes. Also I will look into your Forthcoming PR.

**Comment by tbenbrahim** [comment]
@kevzlou7979 , yI will close this, the problem is only with setValues/getSelected values and may not be related, I will open a separate issue for the discussion and a separate issue for the multiple value issue. Thanks

**Comment by kevzlou7979** [comment]
Hi @tbenbrahim yeah sure open a separate issue
