### ISSUE TITLE
MaterialComboBox: bug with set value for first value

### ISSUE THREAD

**Issue by tbenbrahim** [GwtMaterialDesign/gwt-material-addins#193]
There is a bug in setValue so that index 0 cannot be selected, due to `if (index > 0) {` rather than `if (index >= 0) {`

PR forthcoming

**Comment by kevzlou7979** [comment]
Duplicate https://github.com/GwtMaterialDesign/gwt-material-addins/issues/171 , Please make use of 2.0-SNAPSHOT instead to see the fixed issues. Thanks
