### ISSUE TITLE
Material ComboBox bug: isEnabled is not working, always returns true

### ISSUE THREAD

**Issue by tbenbrahim** [GwtMaterialDesign/gwt-material-addins#195]
cause, setEnabled does not call super.setEnabled, adding this call fixes it.
Another potential fix is to override isEnabled() to return listbox.isEnabled.

PR forthcoming

**Comment by kevzlou7979** [comment]
What version are you using, it seems that all bugs are belong to master, take note that we fixed this on 2.0-SNAPSHOT.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/c6dc59de4f948691464152e5e572db47a205ee32
