### ISSUE TITLE
MaterialComboBox PlaceHolder works just with empty datasource

### ISSUE THREAD

**Issue by Pasha-gharibi** [GwtMaterialDesign/gwt-material-addins#200]
I have updated to gwt-material-2.8-SNAPSHOT ;
after calling MaterialComboBox.addItem(x,y)  placeholder disappears.
just with an empty datasource it's ok.
Any Idea?
thanks

**Comment by kevzlou7979** [comment]
Placeholder only works with Multiple Selection Type of Combobox. Instead of having placeholders into a single selection try to use label instead.

```xml
<ma:combobox.MaterialComboBox label="Sample Label" />
```

**Comment by Pasha-gharibi** [comment]
thanks, but can I change lable's position next to te combbox or its fixed just above it?

**Comment by Pasha-gharibi** [comment]
There is no difference between Multiple Selection and Single Selection. Image if you want to have a default selection for your combo such as 'NONE' option, then you want to add 'NONE' to your values?

**Comment by kevzlou7979** [comment]
I will try to review this and make possible to have a placeholder even if there's no option.

**Comment by kevzlou7979** [comment]
Hi there, 
I found a solution for the issue and here's the link stating the woraround
http://stackoverflow.com/questions/21413241/how-to-use-placeholder-as-default-value-in-select2-framework

![combo-issue1](https://cloud.githubusercontent.com/assets/3138071/23645024/0be8f22e-0345-11e7-9aed-415ef105b96a.gif)
