### ISSUE TITLE
Rich Editor: replace content with cleared text without triggering event

### ISSUE THREAD

**Issue by wassx** [GwtMaterialDesign/gwt-material-addins#202]
Hi!
The rich editor is a powerful tool. I use it for a customer and first thing I ended up was to clean up the input which the customer PASTEs into the rich editor.
To be exact: email content with styles, links etc,....
I use a JS lib which removes all tags and styles of the richEditor.getHtml() and I try to re-insert / replace the content with the cleaned-up content.
But it's getting pretty difficult without triggering events and retriggering value changes events,...
Or do I miss something?
Any ideas plz?

**Comment by kevzlou7979** [comment]
Hi @wassx  We have implemented this already, try using 2.0-rc3 or 2.0-SNAPSHOT.

Code samples:
```java
 // Value Change Event
 @UiHandler("eventRichEditor")
 void onValueChange(ValueChangeEvent<String> e) {
  GWT.log("Value Change Event : " + eventRichEditor.getHTML());
 }
 // Key Up and Down Events
 @UiHandler("eventRichEditor")
 void onKeyUp(KeyUpEvent e) {
  GWT.log("Key Up : " + eventRichEditor.getHTML());
 }

  @UiHandler("eventRichEditor")
 void onKeyDown(KeyDownEvent e) {
  GWT.log("Key Down : " + eventRichEditor.getHTML());
 }
 // Focus and Blur Events
 @UiHandler("eventRichEditor")
 void onFocus(FocusEvent e) {
  GWT.log("Focus Event : " + eventRichEditor.getHTML());
 }

  @UiHandler("eventRichEditor")
 void onBlur(BlurEvent event) {
  GWT.log("Blur Event : " + eventRichEditor.getHTML());
 }
 // Paste Event
 @UiHandler("eventRichEditor")
 void onPaste(PasteEvent e) {
  GWT.log("Paste : " + eventRichEditor.getHTML());
 }
```

Demo under Events Section
http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#richeditor
