### ISSUE TITLE
Horizontal step-panel width issue

### ISSUE THREAD

**Issue by mpallesen** [GwtMaterialDesign/gwt-material-addins#203]
Hi

When using GWT material 2.0 with IE 11 (and possible other versions), the width of the step contents is limited. 
I can find no ways of stretching the content to 100%. 

The issue can easyly be viewed by visiting http://gwtmaterialdesign.github.io/gwt-material-demo/#steppers and looking on the horizontal examples.

Thanks for a great component!

/Michael

**Comment by kevzlou7979** [comment]
Hi @mpallesen Can you provide a screenshot wherein you see the issue so that We can visualize it easily. Thanks in advance.

**Comment by mpallesen** [comment]
Hi. 

@kevzlou7979, last night i found a solution. When using the "DOM Explorer" in IE i saw that the css style ".horizontal.stepper .step" had an entry position: initial, which had a red underline indicating an error.

In my code i set 
materialStep1.setLayoutPosition(Position.STATIC);
and it looks like this fixes everything.

/Michael

**Comment by kevzlou7979** [comment]
@mpallesen Thanks for the information will do a review and see if it will work on my side and see if there are no regressions.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/5edf287088fe56ea4ff5d0dd7f252ae7e5499f4d
