### ISSUE TITLE
Allow disabling maximize button on Window class or ignore height on maximizing

### ISSUE THREAD

**Issue by rmraya** [GwtMaterialDesign/gwt-material-addins#208]
Hi,

Window widget doesn't work well on Microsoft Edge. Content height is not well calculated on Edge but works fine with other browsers.

To overcome the problem with Edge and content height, I have to set the initial height of Window widgets. That's a problem when you maximize a window because the window expands horizontally but keeps the assigned height.

There are two solutions that would work in this case:

1) Allow disabling the maximize button in Window. If a windows is used for holding a form (my use case), maximizing is not necessary

2) Ignore the height, like width is ignored, when a user clicks the maximize button and make the Window widget use all available space.

Thanks,
Rodolfo

**Comment by reofake** [comment]
This is possible to hide the maximize button like this :
```
window.getIconMaximize().setVisible(false);
```

But there is still a doubleClickEvent on the window toolbar which do the same thing.
Personnaly I used this to prevent changing size :
```
// For a maximized window :
window.getToolbar().addDoubleClickHandler((event) -> { window.setMaximize(false); });
// So for a non maximized window :
window.getToolbar().addDoubleClickHandler((event) -> { window.setMaximize(true); });
```

Hope it helped you :)

**Comment by rmraya** [comment]
Thanks a lot, that helps.

**Comment by kevzlou7979** [comment]
The default transition of maximize is ok at least on v1 and v2 we will move on and discuss if we can support vertical transition.

**Comment by rmraya** [comment]
Transition fails on Edge when height value was set. The windows is not properly maximized. That's a bug.

**Comment by kevzlou7979** [comment]
I found a solution : having ```height: 100vh; ``` in ```.window.maximize``` class  solived the issue. Will commit now the fixes

**Comment by rmraya** [comment]
Maximizing works fine in current snapshot. Thanks.
