### ISSUE TITLE
JS exeption if I add/remove/add a slot that contains a MaterialSplitPanel

### ISSUE THREAD

**Issue by medmile** [GwtMaterialDesign/gwt-material-addins#209]
this issue is in the 2.0_rc4 version.

**Comment by kevzlou7979** [comment]
Hi @medmile ,

Can you submit the log error?, Thanks in advance.

**Comment by kevzlou7979** [comment]
Can you submit also a sample project so that we will easily reproduce your issue?

**Comment by medmile** [comment]
I don't know how to get all logs. But in the material-design-demo if i go to the https://gwtmaterialdesign.github.io/gwt-material-demo/#splitpanel , then link Subheader and then link Split Panel, the function onReveal() don't work and title is "Subheader".
![image](https://cloud.githubusercontent.com/assets/2050606/24348597/e96b118c-12e4-11e7-8e58-4d81f94ba03e.png)

**Comment by kevzlou7979** [comment]
Thanks, I am able to reproduce this issue. I am working on the solution for this issue.

**Comment by kevzlou7979** [comment]
Fixed  via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/a538d4f58c25bc8af1030a1bb48da1628fa592d2
