### ISSUE TITLE
Material FileUpload

### ISSUE THREAD

**Issue by fredrickRoyal** [GwtMaterialDesign/gwt-material-addins#21]
We are missing a file upload widget. im sure everyone else is waiting for this widget out there.

**Comment by kevzlou7979** [comment]
+1 Will do some research on how we can integrate this feature

**Comment by kevzlou7979** [comment]
We have decided to use http://www.dropzonejs.com/# to be our external js api to develop our gwt-uploader, any other recommendation?

**Comment by kevzlou7979** [comment]
https://github.com/GwtMaterialDesign/gwt-material-addins/pull/38

**Comment by kevzlou7979** [comment]
Ok we provided the Clien UI for the file upload. The server side will be up to users for their own implementation. The main property for this widget is the form url and also the form method (Post or Put ) and we added handlers to provide better controls.
