### ISSUE TITLE
FIleUploader post data

### ISSUE THREAD

**Issue by chvndb** [GwtMaterialDesign/gwt-material-addins#210]
Is there any way to add post data to an upload request?

**Comment by kevzlou7979** [comment]
Hi there you can make use of parameter ```method='POST'``` and then it's up to you to build the server side structure to get you POST Data.

**Comment by chvndb** [comment]
Sorry, should have clarified. 

Is there a way to programmatically add post data from the `MaterialFileUploader` abstraction? 

Currently (CR4), it is possible to add handlers such as the `SendingHandler, but I do not see how to access the form data from the `SendingEvent` argument. Am I missing something?
