### ISSUE TITLE
Autocomplete list width is fixed, problem with overflow 

### ISSUE THREAD

**Issue by saso5** [GwtMaterialDesign/gwt-material-addins#215]
Shuldn't it be 'min-width: 300px'?

![image](https://cloud.githubusercontent.com/assets/26303578/24579957/0481d4d2-1700-11e7-8dc4-0ee82d0f97a9.png)

![image](https://cloud.githubusercontent.com/assets/26303578/24579990/bda93d56-1700-11e7-9c10-083ce524ae64.png)

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/c64843112750e71deaccc3a73c08b65975835330

**Comment by saso5** [comment]
Tnx for a quick fix!
