### ISSUE TITLE
MaterialWindow change default clickHandler for close icon

### ISSUE THREAD

**Issue by matam** [GwtMaterialDesign/gwt-material-addins#217]
Please consider to add method to remove or override clickHandler for iconClose.
I'm using windows to add some data and when user close unsaved data using this button, receiving warring.
Now, in my project I extend MaterialWindow and override close() method.

**Comment by kevzlou7979** [comment]
@matam I added a flag property wherein you can prevent the close icon by closing it. Please try the code below for the custom implementation.

```java
        window.setPreventClose(true);
        window.getIconClose().addClickHandler(clickEvent -> {
            MaterialToast.fireToast("Prompt any warning here...");
        });
```

Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/50197d03c67ca1b14a6a5b476830fc05f78cf1e9

**Comment by matam** [comment]
Yes it's working.
Thx.
