### ISSUE TITLE
Combobox multiple values and enter

### ISSUE THREAD

**Issue by mvanrobaeys** [GwtMaterialDesign/gwt-material-addins#218]
Steps to repoduce: 
1)  Demo site combobox: Label and placeholder (just need a multiple selection combobox)
2)  Type in "ala", alaska is presented
3)  Press enter
4)  Result is "alaska" and "ala" , see screenshot.  Would expect only "alaska" to appear.

![image](https://cloud.githubusercontent.com/assets/18280223/24679013/2488e2f4-198d-11e7-9da9-d983ef09ae4e.png)

Additionaly, is there an event to listen to if the user types something in and presses enter (or tab) that is not recognized within the default values?

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/dbd999f5a768286417d5b1f9df36cc3b92d6b24f
