### ISSUE TITLE
Regressions on MaterialAutoComplete

### ISSUE THREAD

**Issue by 8vale8** [GwtMaterialDesign/gwt-material-addins#22]
After the last commit on MaterialAutocomplete its behaviour has changed, I would like to understand if this is intentional because I am currently using a previous version of the component in production and updating it now would cause lots of regressions:

- There is no MaterialChipProvider anymore
- The style of the suggestbox is no more the same of MaterialListBox 
- The property "directInputAllowed" has been removed. 
- If directInputAllowed was true there was no default selection on the first element of the suggestions list so that the user could specify a substring of a suggestion as keyword. This is not possible anymore.

Thanks

**Comment by kevzlou7979** [comment]
Yes we are fixing some functions inside this component.

**Comment by 8vale8** [comment]
Ok, so do you plan to restore the features I listed before?

**Comment by kevzlou7979** [comment]
yes

**Comment by drmzperx** [comment]
I would like to extend the list above with the following issues:

- If preload some suggested string into the widget and after extend this with more element the widget is suggest only one element at the same time always. So I cannot choice between suggestions. (On Chrome 48.0.2564.116 (64-bit), linux. and Firefox 26, and Chromium 37.0.2062.120 Ubuntu 12.04 (281580) (64-bit)). See picture:
![gwt-mat-ss-01](https://cloud.githubusercontent.com/assets/16454679/13551571/bb1b933c-e33e-11e5-8ac5-e2bb5c5caea5.jpg)

- If I use the MaterialAutoComplet widget without preloaded elements, suggest more string, but show only one line with little scollbar smilary to the above bug, but with more elements (On Chrome 48.0.2564.116 (64-bit), linux and Chromium 37.0.2062.120 Ubuntu 12.04 (281580) (64-bit)).

**Comment by blazs93** [comment]
I changed from 1.5-SNAPSHOT to 1.5.0-SNAPSHOT and the following bug appeared: 
I preloaded a suggested string, and it worked with 1.5:
![2](https://cloud.githubusercontent.com/assets/11553017/13899158/b8dd0c10-ede6-11e5-94b1-68e30629650d.PNG)
With 1.5.0 didn't:
![1](https://cloud.githubusercontent.com/assets/11553017/13899164/e627525c-ede6-11e5-8bf3-1aedd84ce587.PNG)
Any idea?

**Comment by kevzlou7979** [comment]
This bug is on process we are reverting the material autocomplete to avoid those bugs

**Comment by kevzlou7979** [comment]
Ok Merged the PR made by @gilberto-torrezan https://github.com/GwtMaterialDesign/gwt-material-addins/pull/35
