### ISSUE TITLE
Menu-subMenu with icons

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material-addins#220]
> Hi, the menu has a strange behaviour (with 2.0-rc4 - Chrome 57/Firefox 52 ) when I put an icon to a sub-menu that has a father with an icon. (see the xml example attached, the bug comes out on menu "New")

Reported by @MarcoCucchi

[TestMenu.ui.xml.txt](https://github.com/GwtMaterialDesign/gwt-material-addins/files/913069/TestMenu.ui.xml.txt)

**Comment by kevzlou7979** [comment]
@MarcoCucchi I tested the code you've shared and 2.0-SNAPSHOT fixed this already. Can you confirm? Also please show us a screenshot that causes the issue.

![image](https://cloud.githubusercontent.com/assets/3138071/24908497/ccd702e6-1ef2-11e7-8c2b-00042f5c10c8.png)

**Comment by MarcoCucchi** [comment]
yes sure, btw I was sure that this bug was fixed. (I'm using the 2.0-rc4 version)

![bug](https://cloud.githubusercontent.com/assets/13817916/24924022/ab3199d4-1ef3-11e7-9453-2801f79100a9.gif)

**Comment by kevzlou7979** [comment]
This will be resolved in rc5
