### ISSUE TITLE
MaterialComboBox don't resize when error message happens

### ISSUE THREAD

**Issue by medmile** [GwtMaterialDesign/gwt-material-addins#227]
MaterialComboBox don't resize when error message happens:
![image](https://cloud.githubusercontent.com/assets/2050606/25339379/34cc099c-290b-11e7-9f2c-06799debb2cc.png)

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commits/release_2.0

Manual Test
![combobox-error](https://cloud.githubusercontent.com/assets/3138071/25376903/60b6beee-29d8-11e7-80c1-156ee5a4be1e.gif)
