### ISSUE TITLE
MaterialComboBox function "public Option addItem(String text, T value)" return null always

### ISSUE THREAD

**Issue by medmile** [GwtMaterialDesign/gwt-material-addins#228]
MaterialComboBox function "public Option addItem(String text, T value)" return null always
![image](https://cloud.githubusercontent.com/assets/2050606/25424307/9cde6dd4-2a70-11e7-96d9-a9955a4b43ed.png)

**Comment by kevzlou7979** [comment]
Thanks for this I will review this.

**Comment by kevzlou7979** [comment]
Fixed and added JUnit Test https://github.com/GwtMaterialDesign/gwt-material-addins/commit/c961e239688b0d45ae159bf5896e04b4b34f0b71
