### ISSUE TITLE
TimePicker - Layout Issue on Mobile and Large screens

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material-addins#230]
It seems that time picker is not positioned well, with absolute position the timepicker is moving up and down in tiny motion plus the overlay is not positioned well.

![timepicker-issue](https://cloud.githubusercontent.com/assets/3138071/25610348/8186919e-2f55-11e7-8fa3-f3de64b46d75.gif)

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/acf5e538b2c29b4e7c99f4ea6098c64f545b4946

**Comment by BenDol** [comment]
does this break other implementations?

**Comment by kevzlou7979** [comment]
No it's just specific to clock-overlay not other overlays

**Comment by BenDol** [comment]
I'm meaning when used on the desktop or other devices is this still functional?

**Comment by kevzlou7979** [comment]
Yeah tested on Mobile and Desktop , also the positioning of all overlay must be fixed - that's why I updated it from ```absolute``` to ```fix```.

**Comment by BenDol** [comment]
Okay :+1:
