### ISSUE TITLE
Subheader - Scrollable collection without header 

### ISSUE THREAD

**Issue by vegegoku** [GwtMaterialDesign/gwt-material-addins#235]
Dears
I am trying to make a collection without a header, so i used the subheader addins, but i removed the MaterialSubHeader tag, now in the first render it works perfectly, but whenever i scroll a small header appears at the top like the screen-shot below

![subheader](https://cloud.githubusercontent.com/assets/5379625/26754621/d8ae3e96-4886-11e7-8875-3c90e77c4245.gif)

is there any way to hide this header, or at least to hide it when i scroll to the top most item?

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/2e9af9852f70e112c56f5386fb47ade9eabb2580
