### ISSUE TITLE
Cursor after opening a Window (on 1.5 snapshot)

### ISSUE THREAD

**Issue by MarcoCucchi** [GwtMaterialDesign/gwt-material-addins#24]
Hi guys,
after I close a Popup Window the cursor doesn't change to his original shape. 

Can you fix it?

Thanks

![window](https://cloud.githubusercontent.com/assets/13817916/13556602/e604f166-e3dd-11e5-8d72-9e0b0f4a9926.gif)

**Comment by kevzlou7979** [comment]
Ok fixed with commit https://github.com/GwtMaterialDesign/gwt-material-addins/commit/45fa60696e012c10b591d8b27b89577d82ef580e

**Comment by MarcoCucchi** [comment]
ty Mark!
