### ISSUE TITLE
MaterialRichEditor in modal MaterialWindow insert link issue

### ISSUE THREAD

**Issue by pfacmf** [GwtMaterialDesign/gwt-material-addins#240]
When I open MaterialRichEditor in modal MaterialWindow the "Insert Link" dialog is under an overlay.

**Comment by kevzlou7979** [comment]
I've Follow up the issue in the original repository of RichEditro -> MaterialNote

https://github.com/Cerealkillerway/materialNote/issues/32

**Comment by kevzlou7979** [comment]
This fixed not only on Link Modal but also other modals.

![240](https://user-images.githubusercontent.com/3138071/27821901-70cc42ec-60d6-11e7-9d74-9111e9a3ac78.gif)

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/203c6c4704ec1bf3f8605624b3efaf22f63a62be
