### ISSUE TITLE
More control over MaterialWindow dragging

### ISSUE THREAD

**Issue by gkresic** [GwtMaterialDesign/gwt-material-addins#250]
`MaterialWindow` exposes only one method for controlling how window can be dragged around: `setDndArea(Object)`. I believe there should be a way to control both `Axis`, `Restriction`s and even inertia.

If we could agree what would be the best way to accomplish this, I could provide PR.

My proposal would be to, in addition to existing `build()` method, provide two additional `protected` "builder" methods that subclasses could override:

```
protected JsDragOptions buildDragOptions() {
	// from current MaterialWindow.build()
	return MaterialDnd.draggable(this, JsDragOptions.create(new Restriction("body", true, 0, 0, 1.2, 1)));
}
```

and

```
protected MaterialDnd buildDnd() {
	// from current MaterialWindow.build()
	MaterialDnd dnd = MaterialDnd.draggable(buildDragOptions());
	dnd.ignoreFrom(".content, .window-action");
	return dnd;
}
```

That way, most users could override just `buildDragOptions()` and those who want utter control over DND, could override `buildDnd()` itself.

**Comment by kevzlou7979** [comment]
@gkresic Yup you can submit PR, that would be awesome
