### ISSUE TITLE
MaterialCameraCapture - Replace OLD API with new standard Navigator API.

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material-addins#261]
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

**Comment by BenDol** [comment]
We will be switching over to elemental2 for these changes.

**Comment by kevzlou7979** [comment]
Yeah if it's available and stable. But for now let's just use plain JSInterop.

**Comment by BenDol** [comment]
Elemental2 uses JSInterop, this can be a task I take on at some point soon.
