### ISSUE TITLE
MaterialStepper: logic executed at onLoad method can create problems when the component is reattached to the DOM tree.

### ISSUE THREAD

**Issue by gilberto-torrezan** [GwtMaterialDesign/gwt-material-addins#27]
The `onLoad()` method of the Widget system is called by the `onAttach()` of the Widget base class, which is turn "is called when a widget is attached to the browser's document." (from the [javadoc](http://www.gwtproject.org/javadoc/latest/com/google/gwt/user/client/ui/Widget.html#onAttach())).

In other words, every time the widget is attached to the DOM tree, the `onLoad()` method is called.

That becomes a problem when the logic inside the method changes the state of the widget. For instance, on MaterialStepper:

```java
    @Override
    protected void onLoad() {
        super.onLoad();
        goToStep(1);
    }
```
Every time the component is reattached, it activates the first step. That's a problem when you have a persistent view where the user can come and go.

The MaterialStep have similar problem:

```java
    @Override
    protected void onLoad() {
        super.onLoad();
        if(getParent() instanceof MaterialStepper){
            stepper = (MaterialStepper) getParent();
            if(stepper.getAxis() == Axis.HORIZONTAL){
                conCircle.add(divTitle);
                conCircle.add(divLine);
                conCircle.add(divDescription);
            }else{
                conBody.insert(divTitle, 0);
                conCircle.add(divLine);
            }

        }
        conCircle.addClickHandler(new ClickHandler() {
            @Override
            public void onClick(ClickEvent event) {
                stepper.goToStep(step);
            }
        });
    }
```

In this case, the layout is redone on every attach, and a click handler is added on every attach. That can lead to multiple click handlers on the component over time.

**Comment by kevzlou7979** [comment]
Ok this was fixed by PR https://github.com/GwtMaterialDesign/gwt-material-addins/pull/28. Again thanks for the PR
