### ISSUE TITLE
MaterialWindow does not support HeaderPanel

### ISSUE THREAD

**Issue by rmraya** [GwtMaterialDesign/gwt-material-addins#274]
Hi,

If you add a HeaderPanel to a MaterialWindow it is not displayed.

Try to reproduce with code like this:

		windowButton.addClickHandler(new ClickHandler() {
			
			@Override
			public void onClick(ClickEvent event) {
				HeaderPanel panel = new HeaderPanel();
				panel.setHeaderWidget(new MaterialLabel("Header label"));;
				panel.setContentWidget(new MaterialLabel("Center label"));
				MaterialWindow window = new MaterialWindow();
				window.add(panel);
				window.open();
			}
		});

**Comment by kevzlou7979** [comment]
Please follow this process.
```
MaterialWindow window = new MaterialWindow();
window.getContent().add(headerPanel);

```

**Comment by rmraya** [comment]
Hi Mark,

Your solution doesn't work. It does not show the HeaderPanel inside the window. Only the tithe bar is displayed.

**Comment by kevzlou7979** [comment]
What version of GMD are you using?

**Comment by rmraya** [comment]
I tested on branch release_2.0 compiled a week ago.

**Comment by kevzlou7979** [comment]
I just checked that the HeaderPanel GWT Widget sets the visibility to hidden that's why it looks like its empty. Why now just use MaterialPanel instead , or if you want to layout them just make use of MaterialRow and MaterialColumn

**Comment by rmraya** [comment]
MaterialPanel does not work. I want to put a large table in the window and the buttons that control add/edit/remove should be in the header. MaterialPanel scrolls the content and buttons become invisible.

**Comment by rmraya** [comment]
Does HeaderPanel work inside a MaterialWindow now?
