### ISSUE TITLE
MaterialAutoComplete not put the selected item correctly by press the enter or click on it

### ISSUE THREAD

**Issue by drmzperx** [GwtMaterialDesign/gwt-material-addins#278]
Hi,

when I press the enter button inside the MaterialAutoComplete element, firstly put the pretyped string created a chips and also the suggested text not the chips element. After I press the enter again the MaterialAutoComplete create the chips element for the right suggested text. This issue appeared after upgrade GMD 2.0-rc5 to rc7, rc6 not tested.

![materialautocomplete_bug_2017-11-03](https://user-images.githubusercontent.com/16454679/32389191-4c2106e0-c0ca-11e7-8f59-f4595f3a11f7.jpg)

Affected versions:
Chromium 62, Firefox 56, GWT 2.8.0 and 2.8.1, GMD 2.0-rc7 and 2.1-SNAPSHOT

**Comment by kevzlou7979** [comment]
Hi @drmzperx Can you please elaborate more how to reproduce the bug? Thanks in advance :)

**Comment by drmzperx** [comment]
Yes, I try it:

The affected ui.xml file contains:
`xmlns:a="urn:import:gwt.material.design.addins.client.autocomplete"`

`<a:MaterialAutoComplete ui:field="acIng" placeholder="Add ingredients" limit="50"/>`

The affected part of java file contains:
```
    public void setIngSub(List<IngSubViewDTO> list) {
        IngSubSuggestOracle o = new IngSubSuggestOracle(list);
        acIng.setSuggestions(o);
    }
```
or also

```
    public void setIngSub(List<IngSubViewDTO> list) {
        listIngSub = list;
        MaterialSuggestionOracle s = new MaterialSuggestionOracle();
        for (IngSubViewDTO m : listIngSub) {
            s.add(m.getInci());
        }
        acIng.setSuggestions(s);
    }
```

Please find attached the IngSubSuggestOracle.java file.

The bug also occurs in Firefox Quantum 57.0.

[IngSubSuggestOracle.java.zip](https://github.com/GwtMaterialDesign/gwt-material-addins/files/1491369/IngSubSuggestOracle.java.zip)

Thanks!

**Comment by kevzlou7979** [comment]
I don't think it's a bug coming from GMD side, this should be an implementation issue.

**Comment by kevzlou7979** [comment]
I can confirm that Autocomplete is working well in the demo showcase and passing the required unit test case. If you can write a unit test that will be good.

**Comment by kevzlou7979** [comment]
Sorry for the late response, Digging this issue in , I've luckily notice the issue your talking. I'm working now on this. Thanks by the way for catching this up.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/2ec190ec40caa5f73575c3be212063f887dd624d

**Comment by drmzperx** [comment]
Thank you, it's working perfectly!
