### ISSUE TITLE
MaterialTreeItem - setUrl() does not update the image

### ISSUE THREAD

**Issue by fzamagni** [GwtMaterialDesign/gwt-material-addins#282]
Hi,
I'm using TreeView to represent financial statements, and I have to change the image of a MaterialTreeItem depending on it's state: open-folder-image if **open**, close-folder-image if **close**.
I tried to register an `OpenHandler` and a `CloseHandler` for the tree to change the image with the `MaterialTreeItem.setUrl()` method, but it doesn't work.
Can you help me to resolve this issue?
Thanks in Advance.
Fausto

GWT Material Design 1.6.2, GWT Material Design Addins 1.6.2, Java 7, GWT 2.7.0

**Comment by kevzlou7979** [comment]
Thanks for this, I got easily reproduce the issue, so now starting 2.0.1 this issue will be fixed.

**Comment by kevzlou7979** [comment]
Fixed and added unit test via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/7cdc242c842e78b2cdb44ddde8a57ae3cc76e135
