### ISSUE TITLE
MaterialComboBox.setSingleValue fires ValueChangeEvent with wrong values

### ISSUE THREAD

**Issue by gkresic** [GwtMaterialDesign/gwt-material-addins#291]
Looking at [MaterialComboBox.setSingleValue(T, boolean)](https://github.com/GwtMaterialDesign/gwt-material-addins/blob/master/src/main/java/gwt/material/design/addins/client/combobox/MaterialComboBox.java#L477) isn't it wrong to use `values` as new value (`values` contains **all** possible items in combo, not newly selected one)? Shouldn't it be something like `Collections.singletonList(value)`?

**Comment by kevzlou7979** [comment]
Oh yeah your're right, nice catch :+1: Will patch this on 2.0.1

**Comment by gkresic** [comment]
It's been a while, but if I remember correctly, change was not necessary in #471:
```
int index = this.values.indexOf(value);
```
but at #477 where event fires:
```
ValueChangeEvent.fireIfNotEqual(this, before, Collections.singletonList(value));
```

**Comment by kevzlou7979** [comment]
Oops yeah, thanks for this update. I will try to check if something is breaking up on unit tests. If there's nothing then I can patch this up to 2.0.1

**Comment by kevzlou7979** [comment]
Updated the fix https://github.com/GwtMaterialDesign/gwt-material-addins/commit/f0fbb277b651b34a957634f15ef73adaf150368c
