### ISSUE TITLE
MaterialComboBox change current position

### ISSUE THREAD

**Issue by LeshaRB** [GwtMaterialDesign/gwt-material-addins#294]
https://gwtmaterialdesign.github.io/gwt-material-demo/#combobox

Section **Label and Placeholder**

1) Select first item - Alaska
2) Scroll to last item
3) Select last item - Washington
4) See result combobox scroll up to the first selected item - Alaska

I wanted to stay in the previous place

**Comment by kevzlou7979** [comment]
Ok the idea behind the control will be available on ` 2.0.1 `. I added also the way to get the dropdown ` container ` and ` results ` elements to be able to control it. So here's the updated way to scroll the  ` dropdown element ` to top.

``` java
        combobox.addOpenHandler(event -> {
            comboElements.getDropdownResultElement().scrollTop(0);
        });
```

Screenshot :
![addins](https://user-images.githubusercontent.com/3138071/35679635-c9552efc-0792-11e8-9991-8ae2c6d09661.gif)

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/97c81d71c0545d46e2bebbbbf16460ae3c38cd7e

**Comment by LeshaRB** [comment]
Full reproduce 2.0.1

**Comment by kevzlou7979** [comment]
What do you mean @LeshaRB ?

**Comment by LeshaRB** [comment]
I have combobox with 100 items as example
When I choose  item with index 90.
Scrol change its position on top.

And I have to scroll down again
I want him to remember last position, where i choose item

**Comment by LeshaRB** [comment]
Can you reopen ticket?
Because this problem...

**Comment by LeshaRB** [comment]
I add some info
https://vimeo.com/256545844

**Comment by baarb** [comment]
@kevzlou7979 I'm having the same issue and I'm not sure if what you provided is a viable workaround. If the combobox's dropdown is a multiselect, then the dropdown doesn't close. I don't see a situation where the user would want the dropdown to scroll back up to the top result after they select an item, especially if the purpose is for selecting multiple items in the dropdown. It doesn't seem fair to make the user scroll back down every time to select more items. The dropdown shouldn't change position after you select an item in a multiselect combobox- is this something you can reconsider?
