### ISSUE TITLE
MaterialAutoComplete dont't render CHIP with remote data

### ISSUE THREAD

**Issue by MarcoGervasoni** [GwtMaterialDesign/gwt-material-addins#297]
In a MaterialAutoComplete, if the data to load the suggestions come from remote service, the selected item isn't render like a chip.
To reproduce more simply this issue it's enough to populate the MaterialAutoComplete on a button click. To demostrate in attach there are the your demo 2.0 with a little change.

[AutoCompleteView.zip](https://github.com/GwtMaterialDesign/gwt-material-addins/files/1674268/AutoCompleteView.zip)

I think that the issue is caused by method onLoad():
```java 
       registerHandler(suggestBox.addSelectionHandler(selectionEvent -> {
            Suggestion selectedItem = selectionEvent.getSelectedItem();
            itemBox.setValue("");
            if (addItem(selectedItem)) {
                ValueChangeEvent.fire(MaterialAutoComplete.this, getValue());
            }
            itemBox.setFocus(true);
        }));
```

because the handler is added to old istance of suggestBox if I re-use method: 
`setup(SuggestOracle suggestions)`

In the previus version rc6 this issue wasn't present

**Comment by kevzlou7979** [comment]
Ok found out that the ``` suggestbox ``` that has been registered are different each other. And also we need to setup the handler registration only if the suggestbox is creating and instance and added to the Autocomplate container.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/2ec190ec40caa5f73575c3be212063f887dd624d
