### ISSUE TITLE
MaterialAutoComplete misuses suggestions

### ISSUE THREAD

**Issue by gkresic** [GwtMaterialDesign/gwt-material-addins#299]
In `AutocompleteType.TEXT` mode, `MaterialAutoComplete` will pull `displayString` instead of `replacementString` from its `SuggestionOracle`.

From what I can tell, error is in [MaterialAutoComplete.java#L358](https://github.com/GwtMaterialDesign/gwt-material-addins/blob/340f27a79f2e801c3f6f8810a8c3e04a75480805/src/main/java/gwt/material/design/addins/client/autocomplete/MaterialAutoComplete.java#L358).

**Comment by gkresic** [comment]
I'm trying to make a PR, but lots of (unrelated) tests seems to fail on both master and release_2.0.1 branch - is this a known issue? Should I create a PR despite failed tests? To master or to release_2.0.1?

I would prefer to have this fix in any stable branch, I'm assuming this is release_2.0.1?

**Comment by kevzlou7979** [comment]
I would do the update on that part, add some tests on it.

**Comment by kevzlou7979** [comment]
With the current update, I have updated also the demo showcase to have advance checking also on AUTOCOMPLETE TEXT values.

![update](https://user-images.githubusercontent.com/3138071/35662903-b9fcb084-0755-11e8-9be0-48f6d12ef3aa.gif)

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/67af23743e675c32970c608313a59970e4b3264f and updated test cases.
