### ISSUE TITLE
Material Rich Editor (WYSIWYG)

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material-addins#30]
Implementation of Rich Editor using <a href="https://www.tinymce.com/" target="_blank">Tinymce</a> editor.

If you have any good API that we can use please don't hesitate to share your ideas.

**Comment by gilberto-torrezan** [comment]
[CKEditor](http://ckeditor.com/) is another good, well established editor. But I have no preferences.

**Comment by kevzlou7979** [comment]
@gilberto-torrezan Yeah it's one another option. I think we can make us of it later.

**Comment by kevzlou7979** [comment]
I've found one more http://summernote.org/ which supports Paper / Material design component.

**Comment by kevzlou7979** [comment]
Ok I 've developed MaterialNote as rich editor with updated apis. http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#richeditor
