### ISSUE TITLE
RichText: Inserting Picture by image URL twice fails

### ISSUE THREAD

**Issue by chris-malloy-mri** [GwtMaterialDesign/gwt-material-addins#308]
Trying to insert a picture by image URL fails the second time.

Go to https://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#richeditor
and click on the picture in the toolbar. Then add any image URL. It will work the first time but never again.

This is a bug in 2.0.1 and 2.1 snapshot.

**Comment by chris-malloy-mri** [comment]
The issue was actually the click haler getting added multiple times, once for each time the dialog is opened: https://github.com/GwtMaterialDesign/gwt-material-addins/blob/master/src/main/resources/gwt/material/design/addins/client/richeditor/resources/js/material_note.js#L5356

Changing the line
```$imageBtn.click(function(event) {```
to
```$imageBtn.off("click").click(function(event) {```
fixes the issue.

**Comment by kevzlou7979** [comment]
Nice that works, will commit my changes on 2.1
