### ISSUE TITLE
MaterialAutoComplete type="TEXT" not working

### ISSUE THREAD

**Issue by silentsnooc** [GwtMaterialDesign/gwt-material-addins#31]
Playing around with autocomplete I noticed that `type="TEXT"` is not working. Neither setting it in the UiBinder nor setting it programmatically changes the result

    <m.addins:MaterialAutoComplete ui:field="acTool" placeholder="test" type="TEXT"/>

**Comment by kevzlou7979** [comment]
Duplicate https://github.com/GwtMaterialDesign/gwt-material-addins/issues/61
