### ISSUE TITLE
Circular progress - Text Alignment issue

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material-addins#313]
![screenshot at may 17 10-09-52](https://user-images.githubusercontent.com/39285900/40153298-c4eaa416-59bb-11e8-8e55-01f45c521cf8.png)

Demo https://gwtmaterialdesign.github.io/gwt-material-demo/2.1/#circularProgress

**Comment by kevzlou7979** [comment]
@marecrismatias1 Ready for test
