### ISSUE TITLE
Camera - Not working on lower browser

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material-addins#314]
This is not a bug but still we need to show something to the user that Browser is not supported.

![image](https://user-images.githubusercontent.com/39285900/40160752-29a6453e-59e1-11e8-809f-8c11c69af3b7.png)

**Comment by kevzlou7979** [comment]
The output of this might display a ` Feature not supported ` - Will be updating the demo to have this kind of result.

**Comment by kevzlou7979** [comment]
Expected Result for Not Supported Camera
![image](https://user-images.githubusercontent.com/3138071/42452049-939a4f68-83bb-11e8-96aa-65545518d84a.png)
