### ISSUE TITLE
DocViewer - No preview is available

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material-addins#320]
![image](https://user-images.githubusercontent.com/39285900/40161564-c1815b4e-59e3-11e8-98a8-0cb5f0c68d2b.png)

Demo https://gwtmaterialdesign.github.io/gwt-material-demo/2.1/#docviewer

**Comment by kevzlou7979** [comment]
This was caused by dead pdf link.
Updated now the pdf link in the demo showcase.

![image](https://user-images.githubusercontent.com/3138071/40527709-5f4ee17e-6020-11e8-95db-4904ddf0e658.png)

**Comment by marecrismatias1** [comment]
Confirmed in IE11,Safari9,Firefox39,IOS:Safari and Android:Chrome
