### ISSUE TITLE
Empty State Loader (Circular) - The loader is on top of the navigation bar

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material-addins#321]
![screenshot at may 17 10-46-27](https://user-images.githubusercontent.com/39285900/40161634-054f7450-59e4-11e8-926a-40c7ab1d7227.png)

Demo https://gwtmaterialdesign.github.io/gwt-material-demo/2.1/#emptystates

**Comment by kevzlou7979** [comment]
Fixed

![image](https://user-images.githubusercontent.com/3138071/40528027-d916f5f4-6021-11e8-8595-89acd665527b.png)

**Comment by marecrismatias1** [comment]
Confirmed in IE11,Safari9,IOS:Safari,Firefox and Android:Chrome
