### ISSUE TITLE
SplitPanel - Bar sizes are different in size

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material-addins#326]
![screenshot at may 17 13-32-18](https://user-images.githubusercontent.com/39285900/40162325-41ddf3f4-59e6-11e8-86c0-32efd0582bd5.png)

Demo https://gwtmaterialdesign.github.io/gwt-material-demo/2.1/#splitpanel

**Comment by kevzlou7979** [comment]
There's no text now overlapping the splitter bar.
![image](https://user-images.githubusercontent.com/3138071/40526173-3d077f58-6017-11e8-9fea-166d0cc75fe7.png)

Splitterbar sizes now are consistent
![image](https://user-images.githubusercontent.com/3138071/40526188-5bb8e28e-6017-11e8-91de-cca4de450445.png)

Added also to be able to set the splitter line color.
```java
  splitter.setSplitterLineColor(Color.BLUE);
```

**Comment by marecrismatias1** [comment]
Confirmed in IE11,Safari9,Firefox39,IOS:Safari and Android:Chrome
