### ISSUE TITLE
Buttons - IE11 added a blue background once focused on the FLAT Button

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material-addins#327]
![image](https://user-images.githubusercontent.com/39285900/40779876-275e4898-6509-11e8-9e76-587bc5948c11.png)

https://gwtmaterialdesign.github.io/gwt-material-demo/2.1/#buttons under FLAT TYPE

**Comment by kevzlou7979** [comment]
Replacing ` background-color: inherit; ` to ` background-color: transparent; ` solves the issue.

![image](https://user-images.githubusercontent.com/3138071/41888438-03399d3a-7938-11e8-9560-4d4668dd8033.png)

@marecrismatias1 Ready for test
