### ISSUE TITLE
Autocomplete - When typing on the input field the clear or X icon is shown only in IE

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material-addins#328]
![image](https://user-images.githubusercontent.com/39285900/40780037-b6cb68a8-6509-11e8-87a6-c34d3bb827f4.png)

Reference: https://gwtmaterialdesign.github.io/gwt-material-demo/2.1/#autocomplete

**Comment by kevzlou7979** [comment]
Ready for test @marecrismatias1
