### ISSUE TITLE
Autocomplete - SuggestionBox Positioning is not well positioned in IE 

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material-addins#329]
![image](https://user-images.githubusercontent.com/39285900/40780152-046d088c-650a-11e8-9994-dd5404583d81.png)

**Comment by kevzlou7979** [comment]
Fixed and ready for testing @marecrismatias1 

![image](https://user-images.githubusercontent.com/3138071/41776326-ec31402e-7659-11e8-84c8-031ef880a533.png)
