### ISSUE TITLE
MaterialAutoComplete margin="0" padding="0" does not remove margin/padding

### ISSUE THREAD

**Issue by silentsnooc** [GwtMaterialDesign/gwt-material-addins#33]
Setting `padding `and `margin `to `0`

    <m.addins:MaterialAutoComplete ui:field="acSearch" placeholder="Suche.." 
                                   margin="0" padding="0"/>

Does unfortunately not work:

![capture](https://cloud.githubusercontent.com/assets/1429426/13792877/687bf802-eaf4-11e5-9d50-22e20b540f31.PNG)

It appears that `multiValueSuggestBox-list still contributes to size of `MaterialAutoComplete`

![capture2](https://cloud.githubusercontent.com/assets/1429426/13792923/95a4b422-eaf4-11e5-8d22-73ab8c58b228.PNG)

**Comment by kevzlou7979** [comment]
All form fields in gwt-material is strickly having a fixed padding.
