### ISSUE TITLE
Cutout - The circle target is not well positioned in IE11

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material-addins#330]
![image](https://user-images.githubusercontent.com/39285900/40895001-9f1b611c-67df-11e8-8357-a7ba2210867f.png)

Reference: https://gwtmaterialdesign.github.io/gwt-material-demo/2.1/#cutouts

**Comment by kevin-i3** [comment]
This if fixed: 

Changed ` body().scrollTop() ` (which returns alway a 0 offset ) and the solution was to convert it to ` $("html, body").scrollTop() `

**Comment by kevin-i3** [comment]
![cutout](https://user-images.githubusercontent.com/38387414/41950758-3f5d6d24-79fa-11e8-959d-dcc69c46815a.gif)

**Comment by kevzlou7979** [comment]
Updated on IE 11 now ready for tests
