### ISSUE TITLE
Recaptcha - Api Loading issue

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material-addins#332]
![screenshot at may 17 15-52-33](https://user-images.githubusercontent.com/39285900/40895169-6b25ec14-67e0-11e8-9a19-937a8638b0db.png)

Please check the image, I think the problem was the Recaptcha api loading is not well loaded.

**Comment by kevzlou7979** [comment]
Ready for test Updated the Domain Site key @marecrismatias1

**Comment by kevzlou7979** [comment]
![image](https://user-images.githubusercontent.com/3138071/41818791-294a4e3a-77e8-11e8-8052-e573f678aaf9.png)
