### ISSUE TITLE
Rating - Double clicking the rate stars produces blue background in IE

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material-addins#333]
![screenshot at may 31 19-03-07](https://user-images.githubusercontent.com/39285900/40895224-9ce34652-67e0-11e8-9cb1-0a8b7ac48b68.png)

Reference:
https://gwtmaterialdesign.github.io/gwt-material-demo/2.1/#rating

Steps to reproduce
1. Go to the reference Url then navigate to Usage Section.
2. Rate four stars then double click the last star to reproduce the issue.

**Comment by kevzlou7979** [comment]
This was intended behaviour of IE due to highlight select feature.
