### ISSUE TITLE
Incubator - Timer Progress - Not animating

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material-addins#334]
Navigate to  https://gwtmaterialdesign.github.io/gwt-material-demo/2.1/#timer then you will see that the progress timer is not animating
![image](https://user-images.githubusercontent.com/39285900/40895396-c60d76b4-67e1-11e8-9d7b-7869ca24457a.png)

**Comment by kevzlou7979** [comment]
Ok ready for tests , this is now working with IE11+ .
