### ISSUE TITLE
Incubator - InlineSearch - Search keyword is not aligned.

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material-addins#335]
![image](https://user-images.githubusercontent.com/39285900/40895430-064f7dd0-67e2-11e8-8c39-714e1b736f37.png)

Reference
https://gwtmaterialdesign.github.io/gwt-material-demo/2.1/#inline_search

**Comment by kevzlou7979** [comment]
Solved ready for test @marecrismatias1
