### ISSUE TITLE
Incubator - InlineSearch - OnBlur turns the textcolor to white

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material-addins#336]
![image](https://user-images.githubusercontent.com/39285900/40895455-356e5726-67e2-11e8-9d2c-76d07947ce14.png)

**Comment by kevzlou7979** [comment]
This was fixed together with https://github.com/GwtMaterialDesign/gwt-material-addins/issues/335 , Ready now for testing @marecrismatias1
