### ISSUE TITLE
Blueprint - No Image in Safari

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material-addins#340]
![image](https://user-images.githubusercontent.com/39285900/41402784-cfaa3aba-6ff5-11e8-851b-f2baaddeb782.png)

**Comment by kevzlou7979** [comment]
Blueprint now is available on Safari
![image](https://user-images.githubusercontent.com/3138071/41771120-a739db10-7646-11e8-87e9-73c934e559f2.png)

**Comment by kevzlou7979** [comment]
Ready now to test @marecrismatias1
