### ISSUE TITLE
Circular Progress - Responsive feature is not well layout

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material-addins#341]
![image](https://user-images.githubusercontent.com/39285900/41817484-76fa5dd8-77ce-11e8-8579-46c9bff64dca.png)

Go to your IPhone mobile and navigate to https://gwtmaterialdesign.github.io/gwt-material-demo/2.1/#circularProgress under Responsive

**Comment by kevzlou7979** [comment]
@marecrismatias1 Ready now for retest
