### ISSUE TITLE
Autocomplete in Mobile (IOS) Dropdown's layout is messed up

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material-addins#342]
![image](https://user-images.githubusercontent.com/39285900/41817512-1459eac6-77cf-11e8-8b8c-2c822996f061.png)

Navigate to https://gwtmaterialdesign.github.io/gwt-material-demo/2.1/#autocomplete and open one the dropdown and check the dropdown menu item layout.

**Comment by kevzlou7979** [comment]
Similar issue with https://github.com/GwtMaterialDesign/gwt-material/issues/831, ` table td` element is overridden in IOS Devices.

**Comment by marecrismatias1** [comment]
Everything is good now
