### ISSUE TITLE
Masonry in Mobile (IOS) Grid are stacked on each other

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material-addins#343]
![image](https://user-images.githubusercontent.com/39285900/41817679-7f89a414-77d2-11e8-8dff-06c041b4c8c5.png)

**Comment by marecrismatias1** [comment]
Tested in Android device but the issue does not appear only IOS Devices

**Comment by kevzlou7979** [comment]
Same with https://github.com/GwtMaterialDesign/gwt-material-addins/issues/339. This is now ready for test
