### ISSUE TITLE
Window - On mobile the whole Layout is messed up

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material-addins#348]
![image](https://user-images.githubusercontent.com/39285900/41968948-80ceea2e-7a38-11e8-9828-21386605bba6.png)

Go to https://gwtmaterialdesign.github.io/gwt-material-demo/2.1/#window under With Tabs section open the window and you will see that the layout is messed up.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/5427d4d70bbe07aca0911546d30291de4b057038. Smaller screens now by default will have a fullscreen view you can turn it off by setting ` fullscreenOnMobile ` to false

**Comment by kevzlou7979** [comment]
![image](https://user-images.githubusercontent.com/3138071/42425633-8b7c8666-8352-11e8-862a-10a1cc52ae90.png)
