### ISSUE TITLE
Incubator - Language selector bug displayng images.

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material-addins#352]
Sometimes the language selector display the available languagese 2xtimes
![schermata del 2018-06-28 11-07-28](https://user-images.githubusercontent.com/8243955/42276180-31e544a2-7f93-11e8-93b1-262cc1f820fd.png)

**Comment by kevzlou7979** [comment]
What happens in your datatable dropdown menu ? Yup might be related because Language Selector extends MaterialDropdown.

**Comment by andreaht** [comment]
For example if  I have 4 columns: A,B,C,D in datatable dropdown menu happens that i see A,B,C,D,A,B,C,D. The first 4 item works and if I select/deselect the related columns are shown/hidden, the last 4 elemnts displayed in dorpdown don't have effects on the datatable.
It's difficult to repilcate, in case i will post a screenshot.

**Comment by kevzlou7979** [comment]
What version of GMD are you using?

**Comment by andreaht** [comment]
I noted the issue  while using gwt-material-2.1-20180628.085554-278 and gwt-material-table-2.1-20180629.133637-168
