### ISSUE TITLE
Please update the status text design

### ISSUE THREAD

**Issue by ichigo92** [GwtMaterialDesign/gwt-material-addins#354]
Currently i am using version `2.1-SNAPSHOT `of `gwt-material` and `gwt-material-addins`. The problem i am facing is due to the recent change in gwt-material regarding the [status text design commit](https://github.com/GwtMaterialDesign/gwt-material/commit/43187b7d90c70a69828ca0cf858f824551fde3b8)
the `gwt-material-addins` is not compiling because the change has not been accommodated in `gwt-material-addins` yet. Please update the status text design as soon as possible in `gwt-material-addins` as well.
![image](https://user-images.githubusercontent.com/14965332/42745967-ed218794-88ee-11e8-901e-dc2821643d47.png)

**Comment by BenDol** [comment]
The status text updates were applied, but it seems it hasn't been deployed yet. @kevzlou7979

**Comment by kevzlou7979** [comment]
Yup just checked it, it seems that the merged havent applied for some reason, im rerunning the travis. Will ping @ichigo92 once everything is deployed.

**Comment by kevzlou7979** [comment]
Ok deployed now :)

**Comment by ichigo92** [comment]
@BenDol, @kevzlou7979 thank you so much for your fast response, appreciate it.
