### ISSUE TITLE
MaterialAutoComplete, unable to add duplicate item into selection

### ISSUE THREAD

**Issue by kyriosX** [GwtMaterialDesign/gwt-material-addins#355]
E.g. if there are already chips Apple, Potato, then Apple cannot be added from suggestion.

**Comment by kevzlou7979** [comment]
Can you indicate what version of GMD are you using?

**Comment by kyriosX** [comment]
GMD 2.1
It is working on demo, but as I can see there is code at 370-372 of MaterialAutoComplete:
        
        if (suggestionMap.containsKey(suggestion)) {
            return false;
        }

which prevents from duplicates, please verify.

**Comment by kevzlou7979** [comment]
Ok will verify it, when I will be available. Thanks for the catch

**Comment by kevzlou7979** [comment]
We should provide an API on 2.2 with property ``` allowDuplicates ``` for custom input. Will update the backlog about this feature request. https://github.com/GwtMaterialDesign/gwt-material/issues/842
