### ISSUE TITLE
MaterialComboBox<T> doesn't implements Editor<T>

### ISSUE THREAD

**Issue by dardison** [GwtMaterialDesign/gwt-material-addins#360]
I found that it implements ```Editor<List<T>>```, but in case of single selection that should be ```Editor<T>``` I think.
I know I can resolve this with an Adapter  and a Converter like:

```
public interface Converter<T, U> {
        
   public U convertValue(T value);

   public T convertModel(U model);

}

public class EditorAdapter<T, U, E extends Editor<U>> implements CompositeEditor<T, U, E>, LeafValueEditor<T> {
   
   public EditorAdapter(E Editor, Converter<T, U> converter){
       ....
   }

   ....
}
```
But I was thinking that because this is a very common case maybe you were thinking about something else in the library I couldn't found

**Comment by kevzlou7979** [comment]
Added to our 2.2 backlog https://github.com/GwtMaterialDesign/gwt-material/issues/842
