### ISSUE TITLE
AddressLooukup place holder style different

### ISSUE THREAD

**Issue by nseb** [GwtMaterialDesign/gwt-material-addins#361]
HI,
the style place holder of Addresslookup Component is different to MatertialTextBox for example.
![image](https://user-images.githubusercontent.com/6363226/44090807-b42ffd28-9fcb-11e8-9031-d92aa4ea9845.png)

**Comment by kevzlou7979** [comment]
Have you added a grid property to your address finder like:
```
<google:addresslookup.AddressLookup grid="s12"  ui:field="addressLookup" label="Address" />
```

This will align it the same like the textfield. Also make sure you are wrapping it with MaterialRow
