### ISSUE TITLE
Choose background color of material combobox

### ISSUE THREAD

**Issue by rodrigobastosv** [GwtMaterialDesign/gwt-material-addins#363]
I think it would be nice if we could choose a color for background of a specific option while using material combo box

**Comment by rodrigobastosv** [comment]
That's great! But just to clarify, it would be great if it could be possible to change the background color of specific options following some criteria

**Comment by kevzlou7979** [comment]
Updated the GMD 2.2 backlog https://github.com/GwtMaterialDesign/gwt-material/issues/842
