### ISSUE TITLE
Bug changing divider color on MaterialSplitPanel

### ISSUE THREAD

**Issue by rmraya** [GwtMaterialDesign/gwt-material-addins#365]
Hi,

The method setSplitterLineColor() in  class MaterialSplitPanel doesn't work as expected.

Default divider color is black (fixed value defined in the class). If you call

   `panel.setSplitterLineColor(Color.BLUE);`

the line stays black. Analyzing the element in the browser, you can see it is set as:

  `<div class="splitter-bar black blue" style="width: 1.34%;">`

"black" is not removed.

**Comment by kevzlou7979** [comment]
Ok let me investigate it

**Comment by rmraya** [comment]
BTW, the blue example at [https://gwtmaterialdesign.github.io/gwt-material-demo/#splitpanel ](https://gwtmaterialdesign.github.io/gwt-material-demo/#splitpanel ) uses `backgroundColor` instead of the newer `splitterLineColor` 

Changing background color doesn't work for me either. I'm using pure Java code, I don't use UiBinder.

**Comment by kevzlou7979** [comment]
Will commit now the changes in 2.2 branch
