### ISSUE TITLE
MaterialTree: NullPointerException when deselectSelectedItem execute

### ISSUE THREAD

**Issue by xkazama-yukio3** [GwtMaterialDesign/gwt-material-addins#378]
I use MaterialTree.

I thought that I wanted to manually cancel selected state in MaterialTree,
I attempted to use `MaterialTree#deselectSelectedItem()` (added from https://github.com/GwtMaterialDesign/gwt-material-addins/issues/163)
When execute, NullPointer has occurred.

Reason:
By SelectionEvent (selectedItem = null) fired in the `deselectSelectedItem` method,
it occurs in SelectionHandler that is set by MaterialTree itself.

Need a null check in SelectionHandler?

```
for (Widget item : getChildren()) {
    if (item instanceof MaterialTreeItem) {
        clearSelectedStyles((MaterialTreeItem) item);
    }
}
MaterialTreeItem treeItem = event.getSelectedItem();
// Add Check whether tree has selected item
if (treeItem != null) {
	treeItem.addStyleName(AddinsCssName.SELECTED);
}
setSelectedItem(treeItem);
```

**Comment by kevzlou7979** [comment]
You are right, this will also trigger a nullpointerexception. Thanks for the catch will be patching this out.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/6f585ff04076061c5616e9c7434e52a9fae6eec6
