### ISSUE TITLE
ComboBox support for Tab Focus

### ISSUE THREAD

**Issue by kevin-i3** [GwtMaterialDesign/gwt-material-addins#384]
Refer to this thread https://github.com/select2/select2/issues/4025

**Comment by kevin-i3** [comment]
With the change, add also OPENING and CLOSING events for better event handling.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/c78d65e7bf0c7fa924db7e1f72ab591178d1f646
