### ISSUE TITLE
MaterialStepper Vertical no longer works

### ISSUE THREAD

**Issue by kenyons** [GwtMaterialDesign/gwt-material-addins#386]
It seems that the Vertical axis setting is not working in 2.1.1 as even the Vertical section of the demo app is now Horizontal.  I've tried setting it in the UiBinder entry and programatically, but it still turns out horizontal.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/ee5583171588f35848d18ecdf5f58ab241233e8e

**Comment by kevzlou7979** [comment]
This was causing by the `detectOrientation` property , it overrides the desktop behaviour to have Horizontal Axis.
