### ISSUE TITLE
Update to dropzone.js 5.5

### ISSUE THREAD

**Issue by RLHawk1** [GwtMaterialDesign/gwt-material-addins#394]
This is a suggestion/request. Since version 5.0, dropzone.js supports client-size file resizing, which would be very useful to me.

**Comment by kevzlou7979** [comment]
Ok cool will be updating the dropzone version to 5.0

**Comment by kevzlou7979** [comment]
Currently our Dropzone version on GMD was 4.x so I think it might be good to upgrade to latest one, I dont see any Breaking changes. The changelog were just fixes and features which I think we can upgrade into.

**Comment by kevzlou7979** [comment]
@RLHawk1 I will let you know once I implemented the new version upgrade, also please don't hesitate to Test it :)

**Comment by kevzlou7979** [comment]
Follow this ticket for the Addins version upgrades.
