### ISSUE TITLE
Add MaterialSideProfile dark mode support

### ISSUE THREAD

**Issue by beppino** [GwtMaterialDesign/gwt-material-addins#407]
Tested on macOS 10.15.4.
Start application with system in dark mode and switch to light (with MaterialDarkModeToggle). The MaterialSideProfile is losing his layout. 
Not if os is initially set to light mode; all seems remain consistent.

**Comment by kevzlou7979** [comment]
Can you show me the code i can't reproduce on my own.
![2](https://user-images.githubusercontent.com/3138071/80261813-17d58980-86be-11ea-8704-776844c482ed.gif)

Here's the code I used:
```
<ma:sideprofile.MaterialSideProfile url="https://miro.medium.com/max/5760/1*r2AuXvDuxdRWCqvmBhlssw.png">
                <m:MaterialImage url="https://res.cloudinary.com/teepublic/image/private/s--XqBcjwVK--/c_crop,x_10,y_10/c_fit,w_830/c_crop,g_north_west,h_1038,w_1038,x_-104,y_-105/l_upload:v1565806151:production:blanks:vdbwo35fw6qtflw9kezw/fl_layer_apply,g_north_west,x_-215,y_-216/b_rgb:bbb0e4/c_limit,f_jpg,h_630,q_90,w_630/v1548392518/production/designs/4075639_0.jpg  "/>
                <m:MaterialLabel text="GWT Material" textColor="WHITE"/>
                <m:MaterialLink text="gwt-material@gmail.com" activates="dropProfile" iconType="ARROW_DROP_DOWN" iconPosition="RIGHT" textColor="WHITE"/>
            </ma:sideprofile.MaterialSideProfile>
```

**Comment by beppino** [comment]
Sorry, maybe was my fault... I can't reproduce too.
All it's fine with your code. 
Thank you for time loose about this unconfirmed bug...
