### ISSUE TITLE
DateRangePicker in dark-mode

### ISSUE THREAD

**Issue by beppino** [GwtMaterialDesign/gwt-material-addins#408]
I've found a little bug when the dialog for dates selection will open top to the field if no enough space bottom.
The triangle indicator is still white. See image attached.
<img width="390" alt="Screenshot 2020-04-24 at 16 05 45" src="https://user-images.githubusercontent.com/333788/80221675-ed47ea00-8645-11ea-9ce0-30d9789dded8.png">
Chrome 81.0.4044.122, macOS 10.15.4

**Comment by kevzlou7979** [comment]
![image](https://user-images.githubusercontent.com/3138071/80260552-c2e44400-86ba-11ea-92ca-6965bf07e8dc.png)

Patched 2.3.1-SNAPSHOT  https://github.com/GwtMaterialDesign/gwt-material-addins/commit/118229d1da3ea4cc64acca2756c924f4be106371
