### ISSUE TITLE
DateRangePicker multiple issues 

### ISSUE THREAD

**Issue by andreififiita** [GwtMaterialDesign/gwt-material-addins#409]
1. It doesn't work in a popup. Even though the popup opens, nothing happens when I press the any buttons inside.
<img width="1258" alt="Screenshot 2020-05-11 at 12 29 48" src="https://user-images.githubusercontent.com/9675912/81546844-9f401f80-9383-11ea-802f-f003e9fe486a.png">

2. Alignment is off the screen when I activate debug tools. It can remain under the box, and scrollable in window
<img width="1330" alt="Screenshot 2020-05-11 at 12 38 00" src="https://user-images.githubusercontent.com/9675912/81547308-5b99e580-9384-11ea-959c-92bcb3f2724a.png">

3. When I activate time selections, and press apply, the time is not showing up in the textbox. Is there a setter somewhere to activate this (format)?
<img width="720" alt="Screenshot 2020-05-11 at 12 40 29" src="https://user-images.githubusercontent.com/9675912/81547670-d82cc400-9384-11ea-882a-75ccdcf552ec.png">

**Comment by kevzlou7979** [comment]
>1. It doesn't work in a popup. Even though the popup opens, nothing happens when I press the any buttons inside.

Do you use MaterialDialog ?

> 2. Alignment is off the screen when I activate debug tools. It can remain under the box, and scrollable in window

Will take a look on this.

> When I activate time selections, and press apply, the time is not showing up in the textbox. Is there a setter somewhere to activate this (format)?

We might support a default formatting of the date range (Will update the 2.3.1-SNAPSHOT to support it.

**Comment by andreififiita** [comment]
1. No. It is just a normal GWT popup, but i think the issue is the "modal" attribute set to true.
3. If time is selected, after clicking APPLY, it should be displayed somewhere there.
