### ISSUE TITLE
Fontawesome free icons

### ISSUE THREAD

**Issue by beppino** [GwtMaterialDesign/gwt-material-addins#410]
Not all free icons are in the implementation.
An example, https://fontawesome.com/icons/lungs?style=solid, from versione 5.2.0, doesn't exist.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/86e7f6e6cc823bdd6c5e77c7fd9965134d50a59e
