### ISSUE TITLE
SplitterLineColor in nested MaterialSplitPanel not set

### ISSUE THREAD

**Issue by GuidoReith** [GwtMaterialDesign/gwt-material-addins#411]
Having the following example:
<m.addins:MaterialSplitPanel splitterLineColor="RED" axis="VERTICAL" barPosition="60" thickness="8" dock="BOTTOM" height="850px">
	<m.addins:MaterialSplitPanel splitterLineColor="GREEN" barPosition="20" thickness="8" dock="LEFT" height="425px">
		<m:MaterialPanel backgroundColor="GREY_LIGHTEN_2">
			<m:MaterialTitle textAlign="CENTER" title="1"/>
		</m:MaterialPanel>
		<m:MaterialPanel backgroundColor="GREY_LIGHTEN_2">
			<m:MaterialTitle textAlign="CENTER" title="2"/>
		</m:MaterialPanel>
	</m.addins:MaterialSplitPanel>
	<m.addins:MaterialSplitPanel splitterLineColor="BLUE" barPosition="20" thickness="8" dock="LEFT" height="425px">
		<m:MaterialPanel backgroundColor="GREY_LIGHTEN_2">
			<m:MaterialTitle textAlign="CENTER" title="3"/>
		</m:MaterialPanel>
		<m:MaterialPanel backgroundColor="GREY_LIGHTEN_2">
			<m:MaterialTitle textAlign="CENTER" title="4"/>
		</m:MaterialPanel>
	</m.addins:MaterialSplitPanel>
</m.addins:MaterialSplitPanel>

The splitterLineColor="RED" is not set in the split panel with vertical axis. The other splitterLineColor="GREEN" and splitterLineColor="BLUE" are set correct.

**Comment by kevzlou7979** [comment]
Ok will take a look today.

**Comment by kevzlou7979** [comment]
![image](https://user-images.githubusercontent.com/3138071/85806437-982d6f00-b781-11ea-860b-34166e709fd6.png)

Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/d92b07ef16c4ea0c15f3dfab7af9b2730a2ad900
