### ISSUE TITLE
MaterialDnd - support Drop Event

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material-addins#43]
Add drop event handlers and sample showcase on demo site

**Comment by kevzlou7979** [comment]
With the new JSINterop maybe it will be good to include it on 2.0-SNAPSHOT

**Comment by MarcoCucchi** [comment]
Hi Mark, will we have an example of drop events on the 1.6 version?

Thanks.

**Comment by kevzlou7979** [comment]
We will do it on 2.0 as it will be the v2 for dnd

**Comment by kevzlou7979** [comment]
Try to see the first implementation of drop here http://gwtmaterialdesign.github.io/gwt-material-demo/2.0-SNAPSHOT/#dnd

**Comment by MarcoCucchi** [comment]
Ok Mark! (again, you are doing a great job here, keep on!!)
