### ISSUE TITLE
MaterialWindow add to rootpanel on openWindow

### ISSUE THREAD

**Issue by mvanrobaeys** [GwtMaterialDesign/gwt-material-addins#48]
You need to include a materialWindow in your widget to use it.  
OpenWindow should better attach itself to the rootpanel & remove it on close.

**Comment by BenDol** [comment]
Thanks for the suggestion, do you think you could submit a PR demonstrating the fix you are looking for? Any support from the community its greatly appreciated.

**Comment by mvanrobaeys** [comment]
https://github.com/GwtMaterialDesign/gwt-material-addins/pull/67

**Comment by mvanrobaeys** [comment]
Thanks for the quick merge!  Guess this issue can be closed now.
