### ISSUE TITLE
MaterialAutoComplete: there is no addSelectionHandler method, like in standard gwt SuggestBox

### ISSUE THREAD

**Issue by ratuka** [GwtMaterialDesign/gwt-material-addins#50]

**Comment by kevzlou7979** [comment]
We have Value Change Handler but we may include Selection Handler...

**Comment by ratuka** [comment]
btw ValueChangeHandler not works, too :)
(but SelectionHandler is a must, especially when you transiting from a plain gwt app)

**Comment by kevzlou7979** [comment]
Are you using Maven? or Github? for the repositories?

**Comment by ratuka** [comment]
Maven

**Comment by kevzlou7979** [comment]
Ah ok so the latest snapshot is not yet publish , will publish today so that you can check if its working :) Thanks for your patience.

**Comment by ratuka** [comment]
:D sorry for the issues

**Comment by kevzlou7979** [comment]
No worries :)

**Comment by kevzlou7979** [comment]
Ok you can test now https://oss.sonatype.org/content/repositories/snapshots/com/github/gwtmaterialdesign/gwt-material-addins/1.5.0-SNAPSHOT/ It was updated the latest Maven repo for addins 4.14.16
