### ISSUE TITLE
Extending sub-classes of MaterialWidget in a meaningful way (getter/setter methods for private properties)

### ISSUE THREAD

**Issue by kyr0** [GwtMaterialDesign/gwt-material-addins#51]
Hi all,

I noticed that a lot of MaterialWidget sub-classes i.e. MaterialListBox are actually composite widgets, managing internal widgets. Let's say, the widget class comes with some members:

        private final ListBox listBox = new ListBox();
        private final Label lblName = new Label();
        private ToggleStyleMixin<ListBox> toggleOldMixin;
        private boolean initialized;

Well, you see that they are all declared *private* and thus can't be modified in sub-classes. They also come *without getter and setter methods for the internal properties* quite often. For example, MaterialListBox has no getListBox(), setListBox(), getInitialized(), setInitialized(...), setLabel() and getLabel(). I'm sure there is a concept behind that, but I don't know if that is more important than extensibility.

Currently I don't see any way to extend those widget classes in a meaningful way. Instead of extending, I see myself forced to copy the code of this class to change and adapt it's behavior to my needs and... and loosing any upstream compatibility on that way.

Well... would it be fine for you to change that in all widget classes by adding getter/setter methods for all private member properties? Or do you have any other ideas?

If you are fine with such a change, I'm willing to do that job for any widget class and provide a pull request (if that would speed up the progress to get the change into the snapshot version) :)

Thank you in advance and best,
Aron

**Comment by kyr0** [comment]
ps.: Actually this is an issue for gwt-material and gwt-material-addins (I've chosen the wrong one by accident) but I don't want to cross-post it now.

**Comment by BenDol** [comment]
Thanks for the feedback. The only reason a lot of the Widgets properties have not been opened up is really just that it hasn't been added yet. Access to these properties would be final in that we shouldn't allow custom setting in most cases.

We would be welcoming Pull Requests on any widgets you are able to add getters to for sure.

**Comment by gilberto-torrezan** [comment]
There's a thin line between "not exposing the internal implementation" and "allow better extensibility" when talking about public libraries. While keeping the extensibility is highly desirable, exposing everything can confuse the end user, and even the developer who wants to simply add a new property.

Adding a public setter for the Label, for instance `setLabel`, can potentially create confusion around `setPlaceholder`, `setTitle` and `setTooltip` methods. Of course we can add a javadoc stating that the method is used internally by the component and shouldn't be called unless you know what you are doing, but that's the point of keeping it private in the first place.

In my opinion the main problem rises when you create classes that are supposed to be extended (like abstract classes) with private fields/methods (that happens a lot on GWT itself).

Here on GWT Material, most of the classes are UI Widgets, which inner components can be accessed by the DOM tree and styled by external CSS selectors. The need to extend a Widget would be to modify the existing behaviour of the Widget, which is hard to predict when you first create the Widget library.

**Comment by kyr0** [comment]
@gilberto-torrezan Well, that's a valid point: Public methods like `setLabel()` could confuse users. Maybe there is another way to gain better extensibility while not confusing users with exposing internal implementation: We could, in contrast, change internal properties visibility from `private` to `protected`. 

One could then inherit from a GWT Material widget classes and just change a property if needed. Users of the API would not be confused by additional setter and getter methods.

**Comment by kevzlou7979** [comment]
We have a major update comming to 2.0 which we will allow some access to private UiElement / Widget fields for Complex Widgets (Like ComboBox , Tree etc.)
