### ISSUE TITLE
MaterialClipboard

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material-addins#52]
Support copy / cut clipboard to any material widgets.
Reference : https://clipboardjs.com/

**Comment by BenDol** [comment]
This seems like it would be trivial to implement without an external js library.

**Comment by kevzlou7979** [comment]
Ok will review this :)

**Comment by kevzlou7979** [comment]
We will not focus into this functionality as it can be done without using any addin library.
