### ISSUE TITLE
Can't close or expand Windows on mobile

### ISSUE THREAD

**Issue by BenDol** [GwtMaterialDesign/gwt-material-addins#55]
Tested on OnePlus One with Chrome version 49.0.2623.

Seems like the button clicks aren't invoked for some reason.

Can reproduce it in Chromes dev Toggle Device Mode.

![window-bug](https://cloud.githubusercontent.com/assets/1935706/14742423/433f3828-08f0-11e6-9436-94da20514560.gif)

**Comment by kevzlou7979** [comment]
This one is caused by Draggable Header and it's initialize with MaterialDnd. Will do a prior research into it.

**Comment by kevzlou7979** [comment]
Refered to https://github.com/taye/interact.js/issues/58

**Comment by kevzlou7979** [comment]
Fixed commit - https://github.com/GwtMaterialDesign/gwt-material-addins/commit/e1e8295640ab6ce27a0f1453e554494afe16b041
