### ISSUE TITLE
MaterialRichEditor toolbar popups are hiding immidiately

### ISSUE THREAD

**Issue by zlov** [GwtMaterialDesign/gwt-material-addins#56]
Noticed in our project and reproduced in Demo application v 1.5.0

On [this](http://gwtmaterialdesign.github.io/gwt-material-demo/#richeditor) page for all instances of MRE where setHTML was called when I click any toolbar icon with popup menu it (the popup) becomes hidden right after display.

![richeditorpopups](https://cloud.githubusercontent.com/assets/18423465/14739289/71896750-08a8-11e6-927d-bdf149ee21ca.gif)

**Comment by kevzlou7979** [comment]
I confirmed this one is a bug.

**Comment by kevzlou7979** [comment]
Fixed with this commit - https://github.com/GwtMaterialDesign/gwt-material-addins/commit/cce2fd9ed5d5736c021f9c8b3cd911171ef0f73a

**Comment by kevzlou7979** [comment]
Fixed Demo - http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#richeditor
