### ISSUE TITLE
Dropzone exception

### ISSUE THREAD

**Issue by KenMills** [GwtMaterialDesign/gwt-material-addins#57]
I'm getting an exception when I reenter a page that has the file uploader ui component (whether I display the file uploader or not).

The test app I created has:
Page 1, has a button to go to Page 2
Page 2, has a button to display a dialog with a file uploader

I can show/hide the dialog and the file uploader is displayed fine.

If I go back to Page 1, then attempt to go to Page 2 the exception is seen.

Exception caught: (Error) : Dropzone already attached.com.google.web.bindery.event.shared.UmbrellaException

**Comment by KenMills** [comment]
![dropzone](https://cloud.githubusercontent.com/assets/12837618/14747134/9ab00314-0867-11e6-99d7-3ebd8e9b9f62.gif)

**Comment by kevzlou7979** [comment]
Thanks for the update, will ping once it's debugged.

**Comment by kevzlou7979** [comment]
Got a fixed for this issue, we have to check whether the dropzone has been initialize. Will commit soon my fixed.

**Comment by kevzlou7979** [comment]
Fixed with commit https://github.com/GwtMaterialDesign/gwt-material-addins/commit/19062af8025cd04a7d28d9f27e0399dc4c4b2955 on 1.5.1-Release branch
