### ISSUE TITLE
MaterialRichEditor materialnote is not a function

### ISSUE THREAD

**Issue by mvanrobaeys** [GwtMaterialDesign/gwt-material-addins#60]
```
public class MyApplication implements EntryPoint {
    public void onModuleLoad() {
        RootPanel.get().add(new MaterialRichEditor());
    }
}
```
results in error: Uncaught TypeError: $wnd.jQuery(...).materialnote is not a function

Tested with 1.5.1-SNAPSHOT, with the gwt material demo project setup (just doing above code, not using mvp)

**Comment by mvanrobaeys** [comment]
Forked project to demonstrate the problem: https://github.com/mvanrobaeys/gwt-material-demo

Other addin widgets give same problem (with other js functions), so must be static js injection that is a problem.

**Comment by kevzlou7979** [comment]
This might be the parent issue and discussion https://github.com/GwtMaterialDesign/gwt-material-addins/issues/47

**Comment by kevzlou7979** [comment]
Ok the parent https://github.com/GwtMaterialDesign/gwt-material-addins/issues/47 was already close
