### ISSUE TITLE
JS exeption if I add/remove/add a slot that contains a MaterialSplitPanel

### ISSUE THREAD

**Issue by Milraun** [GwtMaterialDesign/gwt-material-addins#65]
In my application I have a (GWTP) slot that contains a MaterialSplitPanel. If i add another Presenter/Panel to that slot and try to add the Presenter/Panel with the MaterialSplitPanel afterwards I get the following exception:

Caused by: com.google.gwt.core.client.JavaScriptException: (String) : Cannot make a splitter here! '' already has a splitter! Use $('')[0].touchSplitter.destroy(<optional side to remove>) to remove it!

If I use just 'normal' MaterialPanels everything works fine.

**Comment by Milraun** [comment]
Hi,

I could fix that problem by changing the initSplitter Method of the MaterialSplitPanel to:

```java
    private native void initSplitter(Element e,double barPosition, double rightMax, double rightMin, double leftMax, double leftMin, double topMax, double topMin, double bottomMin, double bottomMax, String dock, String orientation) /*-{
      $wnd.jQuery(document).ready(function() {
        var splitted = $wnd.jQuery(e);
        if( splitted[0].touchSplitter == null ) {
           splitted.touchSplit({barPosition: barPosition, thickness: "8px", rightMax: rightMax, rightMin: rightMin, leftMax: leftMax, leftMin: leftMin, topMax: topMax, topMin: topMin, bottomMax: bottomMax, bottomMin: bottomMin, dock: dock, orientation: orientation});
          }
       });
    }-*/;
```

Probably someone could integrate this into the next version (1.5.1 ?)

Jürgen

**Comment by kevzlou7979** [comment]
Thanks for catching the bug.

**Comment by kevzlou7979** [comment]
https://github.com/GwtMaterialDesign/gwt-material-addins/commit/58e9dad1add75e9a0e7f960587ea71d9e42cfda9
