### ISSUE TITLE
MaterialRichEditor: can't get changed html data by calling "getHTML()"

### ISSUE THREAD

**Issue by david2411** [GwtMaterialDesign/gwt-material-addins#66]
When using the RichEditor to show and edit HTML data, i would like to get the edited and changed HTML data. But by caling 'getHTML()' you get the original HTML data, which you inserted by 'setHTML' or 'insertText'. MaterialRichEditor is not usable as editing component :(

You can see this issue also at the demo website: 
http://gwtmaterialdesign.github.io/gwt-material-demo/#richeditor

**Comment by kevzlou7979** [comment]
Hi @david2411,

I tested it working fine?
Can you explain further what's happening?
![image](https://cloud.githubusercontent.com/assets/3138071/15351050/a6ca4152-1d0f-11e6-81f3-e1833c82e738.png)


Best Regards,
Kevin

**Comment by david2411** [comment]
Hi Kevin,
the point is to editing the text within the richeditor. In your video you are setting the content by the method "setHTML". But as an user of an input form you would like to edit your html text with the rich editor (type texts, set your text bold, underlined, take another font etc.). If you do that and call then "getHTML()" you will not get your changed Text, but only your original text you set at the beginning. I will try to take a video too :D

Kind regards,
David

**Comment by david2411** [comment]
![materialdesign_richeditor](https://cloud.githubusercontent.com/assets/19424469/15351765/3192f20e-1ce1-11e6-874f-d7ccf9ee4708.gif)

**Comment by kevzlou7979** [comment]
Ok thanks, I got now the point,

Thanks,
Kevin

**Comment by david2411** [comment]
ok, thanks for your support. We are looking forward to 1.5.1  :+1:

**Comment by kevzlou7979** [comment]
Hi @david2411,

Got it fixed here https://github.com/GwtMaterialDesign/gwt-material-addins/tree/release_1.5.1.

Here, the screenshot below, you can see the developer console logs.
![preview](https://cloud.githubusercontent.com/assets/3138071/15457973/a7ef0b48-20c6-11e6-8884-f1a7a977522a.gif)


Best Regards,
Kevin
