### ISSUE TITLE
MaterialRichEditor gwt editor support

### ISSUE THREAD

**Issue by mvanrobaeys** [GwtMaterialDesign/gwt-material-addins#76]
MaterialRichEditor should be able to bind on String for gwt editor support.

Solution 1)
implement LeafValueEditor<String>
pro: easy
contra: confusing because of getText/setText & getValue/setValue

Solution 2)
Extend from base abstract class.  MaterialValueBox<T> comes close, but would need refactoring.

**Comment by kevzlou7979** [comment]
On Addins 2.0 we extended our RichEditor to AbstractValueWidget which implements Editor<V>, HasEditorErrors<V> and HasValidation. https://github.com/GwtMaterialDesign/gwt-material-addins/blob/release_2.0/src/main/java/gwt/material/design/addins/client/richeditor/base/MaterialRichEditorBase.java#L36 <b>Thanks @BenDol </b>

**Comment by pfacmf** [comment]
I don't think that implementing Editor is enough. I had to implement LeafValueEditor to get the value from the bean to widget at driver.edit(object). The same is true for ComboBox and MaterialListValueBox. 

http://www.gwtproject.org/doc/latest/DevGuideUiEditors.html#LeafValueEditor

I don't fully understand the documentation, but it looks like the setValue and getValue are called on classes implementing LeafValueEditor.

**Comment by kevzlou7979** [comment]
We have implemented a different version of Editor - http://summernote.org/

**Comment by pfacmf** [comment]
This bug is about The GWT Editor framework that "allows data stored in an object graph to be mapped onto a graph of Editors". I want to be able to use the editor, the combobox and the listbox in forms. This bug reports that is not possible to use MaterialRichEditor with GWT Editor Framework ("Data binding for bean-like objects"). This bug was fixed implementing com.google.gwt.editor.Editor interface but it's not working.  MaterialRichEditor, MaterialComboBox and MaterialListValueBox implementing LeafValueEditor fix the problem.

**Comment by mvanrobaeys** [comment]
Correct,
I created a wrapper widget to circumvent this

`public class TextArea extends Composite implements LeafValueEditor<String> {

    private MaterialRichEditor materialRichEditor;

    public TextArea() {
        this.materialRichEditor = new MaterialRichEditor();
        initWidget(materialRichEditor);
    }

    public MaterialRichEditor getMaterialRichEditor(){
        return materialRichEditor;
    }

    @Override
    public String getValue() {
        return materialRichEditor.getHTML();
    }

    @Override
    public void setValue(String value) {
        materialRichEditor.setHTML(value);
    }
}`

**Comment by BenDol** [comment]
I have changed the `MaterialValueWidget` to use the `LeafValueEditor<T>` on the 2.0-SNAPSHOT can you confirm if this solves the problem?

**Comment by pfacmf** [comment]
Yes, the problem is solved when AbstractValueWidget implements LeafValueEditor. Thanks.
