### ISSUE TITLE
File Uploader- getting custom data back from server to client with HTTP response message

### ISSUE THREAD

**Issue by masterdany88** [GwtMaterialDesign/gwt-material-addins#77]
I wonna ask You for some improvment on [File Uploader](https://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#fileuploader).

I would like to get some data (String,Json) from server after successful upload, for example when I will change the name of file on server with HTTP response message.

Currently I can done this when error occurs, and `gwt.material.design.addins.client.fileuploader.events.ErrorEvent.ErrorHandler` is triggered, cause there is an object `private final UploadResponse response;`, that's get access to http header.

For me it will be the best if we would get access to whole Http header object like:
http://www.gwtproject.org/javadoc/latest/com/google/gwt/http/client/Header.html
and Http response codes:
http://www.gwtproject.org/javadoc/latest/com/google/gwt/http/client/Response.html

Print screen with successful upload, where I cannot access status code and message from server response
![fileuploader1](https://cloud.githubusercontent.com/assets/1161910/15701056/265d9d24-27d8-11e6-8681-2d7f2f05eaf7.png)

Print screen with unsuccessful upload, where I can access status code and message from server response with:
```
MaterialFileUploader uploader = new MaterialFileUploader();

uploader.addErrorHandler(new ErrorEvent.ErrorHandler<UploadFile>() {
	    @Override
	    public void onError(ErrorEvent<UploadFile> event) {
		event.getResponse().getCode();
		event.getResponse().getMessage();
	    }
	});
```
![fileuploader2](https://cloud.githubusercontent.com/assets/1161910/15701057/27fb0d9c-27d8-11e6-9bc9-6356bae37878.png)

Here is my server side code for handling upload and returning custom data:
        **return new ResponseEntity<String>("---------------->CREATED", HttpStatus.CREATED);**

```
@RestController()
public class FileController {
    @RequestMapping(value = ServiceRouting.FileService.upload, method = RequestMethod.POST)
    public ResponseEntity<String> upload(HttpServletRequest request, HttpServletResponse response) {
	if (!ServletFileUpload.isMultipartContent(request)) {
	    return new ResponseEntity<String>("---------------->BAD_REQUEST", HttpStatus.BAD_REQUEST);
	} else {
	    try {
		FileHelper.createFileFromHttpServletMultiPartRequest(request, response);
		return new ResponseEntity<String>("---------------->CREATED", HttpStatus.CREATED);
	    } catch (ServletException | IOException e) {
		e.printStackTrace();
		return new ResponseEntity<String>("---------------->INTERNAL_SERVER_ERROR", HttpStatus.INTERNAL_SERVER_ERROR);
	    }
	}
    }
}
```

**Comment by fizzi** [comment]
I think that the problem is here:

https://github.com/GwtMaterialDesign/gwt-material-addins/blob/master/src/main/java/gwt/material/design/addins/client/fileuploader/MaterialFileUploader.java#L224

**Comment by kevzlou7979** [comment]
Ok thanks :)

**Comment by kevzlou7979** [comment]
For more information about the params here http://www.dropzonejs.com/#configuration-options

**Comment by masterdany88** [comment]
I think that parameter xhr just like in the error event should be added to: `SuccessEvent, CompleteEvent, SendingEvent`.

**Comment by kevzlou7979** [comment]
Theres no response param for ``` SuccessEvent ``` only ``` Complete ``` , refer to the doc i've shared :)

**Comment by kevzlou7979** [comment]
Ok I added also the ``` Complete Event ``` will make a PR soon for the code review

**Comment by masterdany88** [comment]
Great. How can I test it?

**Comment by masterdany88** [comment]
It seems that it doesen't do all it supose. In answer we have: 

1. response status code f.e. 201
2. response status message f.e. Created.
3. response body- which is still missing!!!

**Comment by imanbingi** [comment]
Please how do you get the [FormData] to add custom params before sending to server?

**Comment by ajitsnain** [comment]
Is there a way to cancel the currently uploading file ?  I found no such method in this class.
