### ISSUE TITLE
MaterialFileUploader success event

### ISSUE THREAD

**Issue by leforthomas** [GwtMaterialDesign/gwt-material-addins#93]
Could you change

```
zdrop.on('success', function (file) {
                that.@gwt.material.design.addins.client.fileuploader.MaterialFileUploader::fireSuccessEvent(*)(file.name , file.lastModifiedDate , file.size , file.type, file.xhr.status, file.xhr.statusText);
            });
```

to

```
            zdrop.on('success', function (file, response) {
                that.@gwt.material.design.addins.client.fileuploader.MaterialFileUploader::fireSuccessEvent(*)(file.name , file.lastModifiedDate , file.size , file.type, file.xhr.status, file.xhr.statusText, response);
            });

```

?

I need the actual response body sent by my file upload servlet. I use it to send the new file name and its URL as they need to be changed on the fly.
The dropZone actual success event sends the response body.

If there is another way of doing it, I am equally happy but please let me know how it would work.

**Comment by masterdany88** [comment]
@leforthomas so You need response object when upload is success?
If so it has been done already. Look here:
https://github.com/GwtMaterialDesign/gwt-material-addins/pull/87/files#diff-8ee62a8efa022bd004be6f2b5d2156beR268
272 line of code.
or here:
https://github.com/masterdany88/gwt-material-addins/blob/330295fe4d213a74ac727f7e982941225bdc2aa8/src/main/java/gwt/material/design/addins/client/fileuploader/MaterialFileUploader.java

**Comment by kevzlou7979** [comment]
@masterdany88 Can we use / update the return of response as suggested by @leforthomas  for a less  solution?

**Comment by leforthomas** [comment]
Thanks, that will work. I also added the ability to set form parameters in a "programatic" way, if of interest for anybody. I don't think it is possible with the current implementation.

**Comment by kevzlou7979** [comment]
Ok so I will update now the FileUploader to use your solution @leforthomas ,

**Comment by masterdany88** [comment]
@kevzlou7979 yes we can.
